version: "3.8"

services:
  flare-backend:
    image: ghcr.io/dimensiondev/flare:master
    container_name: flare-backend
    restart: unless-stopped

    env_file:
      - .env

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      # STAGE: local
      DOMAINS: api.flareapp.moe -> http://flare-backend:8080

    volumes:
      - https-portal-data:/var/lib/https-portal

    depends_on:
      - flare-backend

volumes:
  https-portal-data:
