/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param type * @param info * @param userId * @param user */
@Serializable
data class AdminShowModerationLogs200ResponseInner(

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "createdAt") val createdAt: kotlin.String,

    @SerialName(value = "type") val type: kotlin.String,

    @SerialName(value = "info") val info: kotlin.String,

    @SerialName(value = "userId") val userId: kotlin.String,

    @SerialName(value = "user") val user: UserDetailed,

)
