/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param upvUser * @param pvUser * @param upvVisitor * @param pvVisitor */
@Serializable
data class ChartsUserPv200Response(

    @SerialName(value = "upv.user") val upvUser: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "pv.user") val pvUser: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "upv.visitor") val upvVisitor: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "pv.visitor") val pvVisitor: kotlin.collections.List<kotlin.Double>,

)
