/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param localTotal * @param localInc * @param localDec * @param remoteTotal * @param remoteInc * @param remoteDec */
@Serializable
data class ChartsUsers200Response(

    @SerialName(value = "local.total") val localTotal: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "local.inc") val localInc: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "local.dec") val localDec: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.total") val remoteTotal: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.inc") val remoteInc: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.dec") val remoteDec: kotlin.collections.List<kotlin.Double>,

)
