/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param fileId * @param folderId * @param name * @param isSensitive * @param comment */
@Serializable
data class DriveFilesUpdateRequest(

    @SerialName(value = "fileId") val fileId: kotlin.String,

    @SerialName(value = "folderId") val folderId: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "isSensitive") val isSensitive: kotlin.Boolean? = null,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

)
