/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param name * @param description * @param location * @param birthday * @param lang * @param avatarId * @param bannerId * @param fields * @param isLocked * @param isExplorable * @param hideOnlineStatus * @param publicReactions * @param carefulBot * @param autoAcceptFollowed * @param noCrawle * @param preventAiLearning * @param isBot * @param isCat * @param injectFeaturedNote * @param receiveAnnouncementEmail * @param alwaysMarkNsfw * @param autoSensitive * @param ffVisibility * @param pinnedPageId * @param mutedWords * @param mutedInstances * @param mutingNotificationTypes * @param emailNotificationTypes * @param alsoKnownAs */
@Serializable
internal data class IUpdateRequest(
    @SerialName(value = "name") val name: kotlin.String? = null,
    @SerialName(value = "description") val description: kotlin.String? = null,
    @SerialName(value = "location") val location: kotlin.String? = null,
    @SerialName(value = "birthday") val birthday: kotlin.String? = null,
    @SerialName(value = "lang") val lang: IUpdateRequest.Lang? = null,
    @SerialName(value = "avatarId") val avatarId: kotlin.String? = null,
    @SerialName(value = "bannerId") val bannerId: kotlin.String? = null,
    @SerialName(value = "fields") val fields: kotlin.collections.List<IUpdateRequestFieldsInner>? = null,
    @SerialName(value = "isLocked") val isLocked: kotlin.Boolean? = null,
    @SerialName(value = "isExplorable") val isExplorable: kotlin.Boolean? = null,
    @SerialName(value = "hideOnlineStatus") val hideOnlineStatus: kotlin.Boolean? = null,
    @SerialName(value = "publicReactions") val publicReactions: kotlin.Boolean? = null,
    @SerialName(value = "carefulBot") val carefulBot: kotlin.Boolean? = null,
    @SerialName(value = "autoAcceptFollowed") val autoAcceptFollowed: kotlin.Boolean? = null,
    @SerialName(value = "noCrawle") val noCrawle: kotlin.Boolean? = null,
    @SerialName(value = "preventAiLearning") val preventAiLearning: kotlin.Boolean? = null,
    @SerialName(value = "isBot") val isBot: kotlin.Boolean? = null,
    @SerialName(value = "isCat") val isCat: kotlin.Boolean? = null,
    @SerialName(value = "injectFeaturedNote") val injectFeaturedNote: kotlin.Boolean? = null,
    @SerialName(value = "receiveAnnouncementEmail") val receiveAnnouncementEmail: kotlin.Boolean? = null,
    @SerialName(value = "alwaysMarkNsfw") val alwaysMarkNsfw: kotlin.Boolean? = null,
    @SerialName(value = "autoSensitive") val autoSensitive: kotlin.Boolean? = null,
    @SerialName(value = "ffVisibility") val ffVisibility: IUpdateRequest.FfVisibility? = null,
    @SerialName(value = "pinnedPageId") val pinnedPageId: kotlin.String? = null,
    // @SerialName(value = "mutedWords") val mutedWords: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "mutedInstances") val mutedInstances: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "mutingNotificationTypes") val mutingNotificationTypes:
        kotlin.collections.List<IUpdateRequest.MutingNotificationTypes>? = null,
    @SerialName(value = "emailNotificationTypes") val emailNotificationTypes: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "alsoKnownAs") val alsoKnownAs: kotlin.collections.Set<kotlin.String>? = null,
) {
    /**
     * *
     * Values: Null,Ach,Ady,Af,AfMinusNA,AfMinusZA,Ak,Ar,ArMinusAR,ArMinusMA,ArMinusSA,AyMinusBO,Az,AzMinusAZ,BeMinusBY,Bg,BgMinusBG,Bn,BnMinusIN,BnMinusBD,Br,BsMinusBA,Ca,CaMinusES,Cak,CkMinusUS,Cs,CsMinusCZ,Cy,CyMinusGB,Da,DaMinusDK,De,DeMinusAT,DeMinusDE,DeMinusCH,Dsb,El,ElMinusGR,En,EnMinusGB,EnMinusAU,EnMinusCA,EnMinusIE,EnMinusIN,EnMinusPI,EnMinusSG,EnMinusUD,EnMinusUS,EnMinusZA,EnAtPirate,Eo,EoMinusEO,Es,EsMinusAR,EsMinus419,EsMinusCL,EsMinusCO,EsMinusEC,EsMinusES,EsMinusLA,EsMinusNI,EsMinusMX,EsMinusUS,EsMinusVE,Et,EtMinusEE,Eu,EuMinusES,Fa,FaMinusIR,FbMinusLT,Ff,Fi,FiMinusFI,Fo,FoMinusFO,Fr,FrMinusCA,FrMinusFR,FrMinusBE,FrMinusCH,FyMinusNL,Ga,GaMinusIE,Gd,Gl,GlMinusES,GnMinusPY,GuMinusIN,Gv,GxMinusGR,He,HeMinusIL,Hi,HiMinusIN,Hr,HrMinusHR,Hsb,Ht,Hu,HuMinusHU,Hy,HyMinusAM,Id,IdMinusID,Is,IsMinusIS,It,ItMinusIT,Ja,JaMinusJP,JvMinusID,KaMinusGE,KkMinusKZ,Km,Kl,KmMinusKH,Kab,Kn,KnMinusIN,Ko,KoMinusKR,KuMinusTR,Kw,La,LaMinusVA,Lb,LiMinusNL,Lt,LtMinusLT,Lv,LvMinusLV,Mai,MgMinusMG,Mk,MkMinusMK,Ml,MlMinusIN,MnMinusMN,Mr,MrMinusIN,Ms,MsMinusMY,Mt,MtMinusMT,My,No,Nb,NbMinusNO,Ne,NeMinusNP,Nl,NlMinusBE,NlMinusNL,NnMinusNO,Oc,OrMinusIN,Pa,PaMinusIN,Pl,PlMinusPL,PsMinusAF,Pt,PtMinusBR,PtMinusPT,QuMinusPE,RmMinusCH,Ro,RoMinusRO,Ru,RuMinusRU,SaMinusIN,SeMinusNO,Sh,SiMinusLK,Sk,SkMinusSK,Sl,SlMinusSI,SoMinusSO,Sq,SqMinusAL,Sr,SrMinusRS,Su,Sv,SvMinusSE,Sw,SwMinusKE,Ta,TaMinusIN,Te,TeMinusIN,Tg,TgMinusTJ,Th,ThMinusTH,Fil,Tlh,Tr,TrMinusTR,TtMinusRU,Uk,UkMinusUA,Ur,UrMinusPK,Uz,UzMinusUZ,Vi,ViMinusVN,XhMinusZA,Yi,YiMinusDE,Zh,ZhMinusHans,ZhMinusHant,ZhMinusCN,ZhMinusHK,ZhMinusSG,ZhMinusTW,ZuMinusZA
     */
    @Serializable
    enum class Lang(
        val value: kotlin.String,
    ) {
        @SerialName(value = "null")
        Null("null"),

        @SerialName(value = "ach")
        Ach("ach"),

        @SerialName(value = "ady")
        Ady("ady"),

        @SerialName(value = "af")
        Af("af"),

        @SerialName(value = "af-NA")
        AfMinusNA("af-NA"),

        @SerialName(value = "af-ZA")
        AfMinusZA("af-ZA"),

        @SerialName(value = "ak")
        Ak("ak"),

        @SerialName(value = "ar")
        Ar("ar"),

        @SerialName(value = "ar-AR")
        ArMinusAR("ar-AR"),

        @SerialName(value = "ar-MA")
        ArMinusMA("ar-MA"),

        @SerialName(value = "ar-SA")
        ArMinusSA("ar-SA"),

        @SerialName(value = "ay-BO")
        AyMinusBO("ay-BO"),

        @SerialName(value = "az")
        Az("az"),

        @SerialName(value = "az-AZ")
        AzMinusAZ("az-AZ"),

        @SerialName(value = "be-BY")
        BeMinusBY("be-BY"),

        @SerialName(value = "bg")
        Bg("bg"),

        @SerialName(value = "bg-BG")
        BgMinusBG("bg-BG"),

        @SerialName(value = "bn")
        Bn("bn"),

        @SerialName(value = "bn-IN")
        BnMinusIN("bn-IN"),

        @SerialName(value = "bn-BD")
        BnMinusBD("bn-BD"),

        @SerialName(value = "br")
        Br("br"),

        @SerialName(value = "bs-BA")
        BsMinusBA("bs-BA"),

        @SerialName(value = "ca")
        Ca("ca"),

        @SerialName(value = "ca-ES")
        CaMinusES("ca-ES"),

        @SerialName(value = "cak")
        Cak("cak"),

        @SerialName(value = "ck-US")
        CkMinusUS("ck-US"),

        @SerialName(value = "cs")
        Cs("cs"),

        @SerialName(value = "cs-CZ")
        CsMinusCZ("cs-CZ"),

        @SerialName(value = "cy")
        Cy("cy"),

        @SerialName(value = "cy-GB")
        CyMinusGB("cy-GB"),

        @SerialName(value = "da")
        Da("da"),

        @SerialName(value = "da-DK")
        DaMinusDK("da-DK"),

        @SerialName(value = "de")
        De("de"),

        @SerialName(value = "de-AT")
        DeMinusAT("de-AT"),

        @SerialName(value = "de-DE")
        DeMinusDE("de-DE"),

        @SerialName(value = "de-CH")
        DeMinusCH("de-CH"),

        @SerialName(value = "dsb")
        Dsb("dsb"),

        @SerialName(value = "el")
        El("el"),

        @SerialName(value = "el-GR")
        ElMinusGR("el-GR"),

        @SerialName(value = "en")
        En("en"),

        @SerialName(value = "en-GB")
        EnMinusGB("en-GB"),

        @SerialName(value = "en-AU")
        EnMinusAU("en-AU"),

        @SerialName(value = "en-CA")
        EnMinusCA("en-CA"),

        @SerialName(value = "en-IE")
        EnMinusIE("en-IE"),

        @SerialName(value = "en-IN")
        EnMinusIN("en-IN"),

        @SerialName(value = "en-PI")
        EnMinusPI("en-PI"),

        @SerialName(value = "en-SG")
        EnMinusSG("en-SG"),

        @SerialName(value = "en-UD")
        EnMinusUD("en-UD"),

        @SerialName(value = "en-US")
        EnMinusUS("en-US"),

        @SerialName(value = "en-ZA")
        EnMinusZA("en-ZA"),

        @SerialName(value = "en@pirate")
        EnAtPirate("en@pirate"),

        @SerialName(value = "eo")
        Eo("eo"),

        @SerialName(value = "eo-EO")
        EoMinusEO("eo-EO"),

        @SerialName(value = "es")
        Es("es"),

        @SerialName(value = "es-AR")
        EsMinusAR("es-AR"),

        @SerialName(value = "es-419")
        EsMinus419("es-419"),

        @SerialName(value = "es-CL")
        EsMinusCL("es-CL"),

        @SerialName(value = "es-CO")
        EsMinusCO("es-CO"),

        @SerialName(value = "es-EC")
        EsMinusEC("es-EC"),

        @SerialName(value = "es-ES")
        EsMinusES("es-ES"),

        @SerialName(value = "es-LA")
        EsMinusLA("es-LA"),

        @SerialName(value = "es-NI")
        EsMinusNI("es-NI"),

        @SerialName(value = "es-MX")
        EsMinusMX("es-MX"),

        @SerialName(value = "es-US")
        EsMinusUS("es-US"),

        @SerialName(value = "es-VE")
        EsMinusVE("es-VE"),

        @SerialName(value = "et")
        Et("et"),

        @SerialName(value = "et-EE")
        EtMinusEE("et-EE"),

        @SerialName(value = "eu")
        Eu("eu"),

        @SerialName(value = "eu-ES")
        EuMinusES("eu-ES"),

        @SerialName(value = "fa")
        Fa("fa"),

        @SerialName(value = "fa-IR")
        FaMinusIR("fa-IR"),

        @SerialName(value = "fb-LT")
        FbMinusLT("fb-LT"),

        @SerialName(value = "ff")
        Ff("ff"),

        @SerialName(value = "fi")
        Fi("fi"),

        @SerialName(value = "fi-FI")
        FiMinusFI("fi-FI"),

        @SerialName(value = "fo")
        Fo("fo"),

        @SerialName(value = "fo-FO")
        FoMinusFO("fo-FO"),

        @SerialName(value = "fr")
        Fr("fr"),

        @SerialName(value = "fr-CA")
        FrMinusCA("fr-CA"),

        @SerialName(value = "fr-FR")
        FrMinusFR("fr-FR"),

        @SerialName(value = "fr-BE")
        FrMinusBE("fr-BE"),

        @SerialName(value = "fr-CH")
        FrMinusCH("fr-CH"),

        @SerialName(value = "fy-NL")
        FyMinusNL("fy-NL"),

        @SerialName(value = "ga")
        Ga("ga"),

        @SerialName(value = "ga-IE")
        GaMinusIE("ga-IE"),

        @SerialName(value = "gd")
        Gd("gd"),

        @SerialName(value = "gl")
        Gl("gl"),

        @SerialName(value = "gl-ES")
        GlMinusES("gl-ES"),

        @SerialName(value = "gn-PY")
        GnMinusPY("gn-PY"),

        @SerialName(value = "gu-IN")
        GuMinusIN("gu-IN"),

        @SerialName(value = "gv")
        Gv("gv"),

        @SerialName(value = "gx-GR")
        GxMinusGR("gx-GR"),

        @SerialName(value = "he")
        He("he"),

        @SerialName(value = "he-IL")
        HeMinusIL("he-IL"),

        @SerialName(value = "hi")
        Hi("hi"),

        @SerialName(value = "hi-IN")
        HiMinusIN("hi-IN"),

        @SerialName(value = "hr")
        Hr("hr"),

        @SerialName(value = "hr-HR")
        HrMinusHR("hr-HR"),

        @SerialName(value = "hsb")
        Hsb("hsb"),

        @SerialName(value = "ht")
        Ht("ht"),

        @SerialName(value = "hu")
        Hu("hu"),

        @SerialName(value = "hu-HU")
        HuMinusHU("hu-HU"),

        @SerialName(value = "hy")
        Hy("hy"),

        @SerialName(value = "hy-AM")
        HyMinusAM("hy-AM"),

        @SerialName(value = "id")
        Id("id"),

        @SerialName(value = "id-ID")
        IdMinusID("id-ID"),

        @SerialName(value = "is")
        Is("is"),

        @SerialName(value = "is-IS")
        IsMinusIS("is-IS"),

        @SerialName(value = "it")
        It("it"),

        @SerialName(value = "it-IT")
        ItMinusIT("it-IT"),

        @SerialName(value = "ja")
        Ja("ja"),

        @SerialName(value = "ja-JP")
        JaMinusJP("ja-JP"),

        @SerialName(value = "jv-ID")
        JvMinusID("jv-ID"),

        @SerialName(value = "ka-GE")
        KaMinusGE("ka-GE"),

        @SerialName(value = "kk-KZ")
        KkMinusKZ("kk-KZ"),

        @SerialName(value = "km")
        Km("km"),

        @SerialName(value = "kl")
        Kl("kl"),

        @SerialName(value = "km-KH")
        KmMinusKH("km-KH"),

        @SerialName(value = "kab")
        Kab("kab"),

        @SerialName(value = "kn")
        Kn("kn"),

        @SerialName(value = "kn-IN")
        KnMinusIN("kn-IN"),

        @SerialName(value = "ko")
        Ko("ko"),

        @SerialName(value = "ko-KR")
        KoMinusKR("ko-KR"),

        @SerialName(value = "ku-TR")
        KuMinusTR("ku-TR"),

        @SerialName(value = "kw")
        Kw("kw"),

        @SerialName(value = "la")
        La("la"),

        @SerialName(value = "la-VA")
        LaMinusVA("la-VA"),

        @SerialName(value = "lb")
        Lb("lb"),

        @SerialName(value = "li-NL")
        LiMinusNL("li-NL"),

        @SerialName(value = "lt")
        Lt("lt"),

        @SerialName(value = "lt-LT")
        LtMinusLT("lt-LT"),

        @SerialName(value = "lv")
        Lv("lv"),

        @SerialName(value = "lv-LV")
        LvMinusLV("lv-LV"),

        @SerialName(value = "mai")
        Mai("mai"),

        @SerialName(value = "mg-MG")
        MgMinusMG("mg-MG"),

        @SerialName(value = "mk")
        Mk("mk"),

        @SerialName(value = "mk-MK")
        MkMinusMK("mk-MK"),

        @SerialName(value = "ml")
        Ml("ml"),

        @SerialName(value = "ml-IN")
        MlMinusIN("ml-IN"),

        @SerialName(value = "mn-MN")
        MnMinusMN("mn-MN"),

        @SerialName(value = "mr")
        Mr("mr"),

        @SerialName(value = "mr-IN")
        MrMinusIN("mr-IN"),

        @SerialName(value = "ms")
        Ms("ms"),

        @SerialName(value = "ms-MY")
        MsMinusMY("ms-MY"),

        @SerialName(value = "mt")
        Mt("mt"),

        @SerialName(value = "mt-MT")
        MtMinusMT("mt-MT"),

        @SerialName(value = "my")
        My("my"),

        @SerialName(value = "no")
        No("no"),

        @SerialName(value = "nb")
        Nb("nb"),

        @SerialName(value = "nb-NO")
        NbMinusNO("nb-NO"),

        @SerialName(value = "ne")
        Ne("ne"),

        @SerialName(value = "ne-NP")
        NeMinusNP("ne-NP"),

        @SerialName(value = "nl")
        Nl("nl"),

        @SerialName(value = "nl-BE")
        NlMinusBE("nl-BE"),

        @SerialName(value = "nl-NL")
        NlMinusNL("nl-NL"),

        @SerialName(value = "nn-NO")
        NnMinusNO("nn-NO"),

        @SerialName(value = "oc")
        Oc("oc"),

        @SerialName(value = "or-IN")
        OrMinusIN("or-IN"),

        @SerialName(value = "pa")
        Pa("pa"),

        @SerialName(value = "pa-IN")
        PaMinusIN("pa-IN"),

        @SerialName(value = "pl")
        Pl("pl"),

        @SerialName(value = "pl-PL")
        PlMinusPL("pl-PL"),

        @SerialName(value = "ps-AF")
        PsMinusAF("ps-AF"),

        @SerialName(value = "pt")
        Pt("pt"),

        @SerialName(value = "pt-BR")
        PtMinusBR("pt-BR"),

        @SerialName(value = "pt-PT")
        PtMinusPT("pt-PT"),

        @SerialName(value = "qu-PE")
        QuMinusPE("qu-PE"),

        @SerialName(value = "rm-CH")
        RmMinusCH("rm-CH"),

        @SerialName(value = "ro")
        Ro("ro"),

        @SerialName(value = "ro-RO")
        RoMinusRO("ro-RO"),

        @SerialName(value = "ru")
        Ru("ru"),

        @SerialName(value = "ru-RU")
        RuMinusRU("ru-RU"),

        @SerialName(value = "sa-IN")
        SaMinusIN("sa-IN"),

        @SerialName(value = "se-NO")
        SeMinusNO("se-NO"),

        @SerialName(value = "sh")
        Sh("sh"),

        @SerialName(value = "si-LK")
        SiMinusLK("si-LK"),

        @SerialName(value = "sk")
        Sk("sk"),

        @SerialName(value = "sk-SK")
        SkMinusSK("sk-SK"),

        @SerialName(value = "sl")
        Sl("sl"),

        @SerialName(value = "sl-SI")
        SlMinusSI("sl-SI"),

        @SerialName(value = "so-SO")
        SoMinusSO("so-SO"),

        @SerialName(value = "sq")
        Sq("sq"),

        @SerialName(value = "sq-AL")
        SqMinusAL("sq-AL"),

        @SerialName(value = "sr")
        Sr("sr"),

        @SerialName(value = "sr-RS")
        SrMinusRS("sr-RS"),

        @SerialName(value = "su")
        Su("su"),

        @SerialName(value = "sv")
        Sv("sv"),

        @SerialName(value = "sv-SE")
        SvMinusSE("sv-SE"),

        @SerialName(value = "sw")
        Sw("sw"),

        @SerialName(value = "sw-KE")
        SwMinusKE("sw-KE"),

        @SerialName(value = "ta")
        Ta("ta"),

        @SerialName(value = "ta-IN")
        TaMinusIN("ta-IN"),

        @SerialName(value = "te")
        Te("te"),

        @SerialName(value = "te-IN")
        TeMinusIN("te-IN"),

        @SerialName(value = "tg")
        Tg("tg"),

        @SerialName(value = "tg-TJ")
        TgMinusTJ("tg-TJ"),

        @SerialName(value = "th")
        Th("th"),

        @SerialName(value = "th-TH")
        ThMinusTH("th-TH"),

        @SerialName(value = "fil")
        Fil("fil"),

        @SerialName(value = "tlh")
        Tlh("tlh"),

        @SerialName(value = "tr")
        Tr("tr"),

        @SerialName(value = "tr-TR")
        TrMinusTR("tr-TR"),

        @SerialName(value = "tt-RU")
        TtMinusRU("tt-RU"),

        @SerialName(value = "uk")
        Uk("uk"),

        @SerialName(value = "uk-UA")
        UkMinusUA("uk-UA"),

        @SerialName(value = "ur")
        Ur("ur"),

        @SerialName(value = "ur-PK")
        UrMinusPK("ur-PK"),

        @SerialName(value = "uz")
        Uz("uz"),

        @SerialName(value = "uz-UZ")
        UzMinusUZ("uz-UZ"),

        @SerialName(value = "vi")
        Vi("vi"),

        @SerialName(value = "vi-VN")
        ViMinusVN("vi-VN"),

        @SerialName(value = "xh-ZA")
        XhMinusZA("xh-ZA"),

        @SerialName(value = "yi")
        Yi("yi"),

        @SerialName(value = "yi-DE")
        YiMinusDE("yi-DE"),

        @SerialName(value = "zh")
        Zh("zh"),

        @SerialName(value = "zh-Hans")
        ZhMinusHans("zh-Hans"),

        @SerialName(value = "zh-Hant")
        ZhMinusHant("zh-Hant"),

        @SerialName(value = "zh-CN")
        ZhMinusCN("zh-CN"),

        @SerialName(value = "zh-HK")
        ZhMinusHK("zh-HK"),

        @SerialName(value = "zh-SG")
        ZhMinusSG("zh-SG"),

        @SerialName(value = "zh-TW")
        ZhMinusTW("zh-TW"),

        @SerialName(value = "zu-ZA")
        ZuMinusZA("zu-ZA"),
    }

    /**
     * *
     * Values: Public,Followers,Private
     */
    @Serializable
    enum class FfVisibility(
        val value: kotlin.String,
    ) {
        @SerialName(value = "public")
        Public("public"),

        @SerialName(value = "followers")
        Followers("followers"),

        @SerialName(value = "private")
        Private("private"),
    }

    /**
     * *
     * Values: Follow,Mention,Reply,Renote,Quote,Reaction,PollEnded,ReceiveFollowRequest,FollowRequestAccepted,AchievementEarned,App
     */
    @Serializable
    enum class MutingNotificationTypes(
        val value: kotlin.String,
    ) {
        @SerialName(value = "follow")
        Follow("follow"),

        @SerialName(value = "mention")
        Mention("mention"),

        @SerialName(value = "reply")
        Reply("reply"),

        @SerialName(value = "renote")
        Renote("renote"),

        @SerialName(value = "quote")
        Quote("quote"),

        @SerialName(value = "reaction")
        Reaction("reaction"),

        @SerialName(value = "pollEnded")
        PollEnded("pollEnded"),

        @SerialName(value = "receiveFollowRequest")
        ReceiveFollowRequest("receiveFollowRequest"),

        @SerialName(value = "followRequestAccepted")
        FollowRequestAccepted("followRequestAccepted"),

        @SerialName(value = "achievementEarned")
        AchievementEarned("achievementEarned"),

        @SerialName(value = "app")
        App("app"),
    }
}
