/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param updatedAt * @param title * @param name * @param summary * @param content * @param variables * @param userId * @param user */
@Serializable
data class Page(
    @SerialName(value = "id") val id: kotlin.String,
    @SerialName(value = "createdAt") val createdAt: kotlin.String,
    @SerialName(value = "updatedAt") val updatedAt: kotlin.String,
    @SerialName(value = "title") val title: kotlin.String,
    @SerialName(value = "name") val name: kotlin.String,
    @SerialName(value = "summary") val summary: kotlin.String? = null,
    @SerialName(value = "content") val content: kotlin.collections.List<PageContent>,
    @SerialName(value = "variables") val variables: kotlin.collections.List<PageContent>,
    @SerialName(value = "userId") val userId: kotlin.String,
    @SerialName(value = "user") val user: UserLite,
)

@Serializable
data class PageContent(
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "type") val type: String? = null,
    @SerialName(value = "text") val text: kotlin.String? = null,
    @SerialName(value = "value") val value: kotlin.String? = null,
    @SerialName(value = "name") val name: kotlin.String? = null,
    @SerialName(value = "args") val args: kotlin.collections.List<PageContent>? = null,
)
