/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.AdditionalMediaInfoCallToActionsUrl

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param visitSite 
 * @param watchNow 
 */
@Serializable

internal data class AdditionalMediaInfoCallToActions (

    @SerialName(value = "visit_site")
    val visitSite: AdditionalMediaInfoCallToActionsUrl? = null,

    @SerialName(value = "watch_now")
    val watchNow: AdditionalMediaInfoCallToActionsUrl? = null

) {


}

