/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ArticleCoverMediaInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param mediaId 
 * @param mediaInfo 
 * @param mediaKey 
 */
@Serializable

internal data class ArticleCoverMedia (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "media_id")
    val mediaId: kotlin.String,

    @SerialName(value = "media_info")
    val mediaInfo: ArticleCoverMediaInfo,

    @SerialName(value = "media_key")
    val mediaKey: kotlin.String

) {


}

