/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ArticleCoverMedia

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param articleId 
 * @param previewText 
 * @param title 
 * @param coverMedia 
 */
@Serializable

internal data class ArticlePreview (

    @SerialName(value = "article_id")
    val articleId: kotlin.Int,

    @SerialName(value = "preview_text")
    val previewText: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "cover_media")
    val coverMedia: ArticleCoverMedia? = null

) {


}

