/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param type
 * @param url
 * @param urlType
 */
@Serializable
internal data class BirdwatchEntityRef(
    @SerialName(value = "type")
    val type: BirdwatchEntityRef.Type,
    @Contextual @SerialName(value = "url")
    val url: String,
    @SerialName(value = "urlType")
    val urlType: BirdwatchEntityRef.UrlType,
    @SerialName(value = "text")
    val text: kotlin.String? = null,
) {
    /**
     *
     *
     * Values: timelineUrl
     */
    @Serializable
    enum class Type(
        val value: kotlin.String,
    ) {
        @SerialName(value = "TimelineUrl")
        timelineUrl("TimelineUrl"),

        @SerialName(value = "TimelineRichTextHashtag")
        TimelineRichTextHashtag("TimelineRichTextHashtag"),
        }

    /**
     *
     *
     * Values: externalUrl
     */
    @Serializable
    enum class UrlType(
        val value: kotlin.String,
    ) {
        @SerialName(value = "ExternalUrl")
        externalUrl("ExternalUrl"),
    }
}
