/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param destinationUrl 
 * @param prompt 
 * @param title 
 */
@Serializable

internal data class BirdwatchPivotCallToAction (

    @Contextual @SerialName(value = "destinationUrl")
    val destinationUrl: kotlin.String,

    @SerialName(value = "prompt")
    val prompt: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String

) {


}

