/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.CommunityActions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param actions 
 * @param id 
 * @param moderationState 
 * @param restId 
 */
@Serializable

internal data class CommunityRelationship (

    @SerialName(value = "actions")
    val actions: CommunityActions,

    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "moderation_state")
    val moderationState: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @SerialName(value = "rest_id")
    val restId: kotlin.String

) {


}

