/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.CommunityDeleteActionResult
import dev.dimension.flare.data.network.xqt.model.CommunityJoinActionResultUnion
import dev.dimension.flare.data.network.xqt.model.CommunityLeaveActionResult
import dev.dimension.flare.data.network.xqt.model.CommunityPinActionResult
import dev.dimension.flare.data.network.xqt.model.CommunityUnpinActionResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param deleteActionResult 
 * @param joinActionResult 
 * @param leaveActionResult 
 * @param pinActionResult 
 * @param unpinActionResult 
 */
@Serializable

internal data class CommunityActions (

    @SerialName(value = "delete_action_result")
    val deleteActionResult: CommunityDeleteActionResult? = null,

    @SerialName(value = "join_action_result")
    val joinActionResult: CommunityJoinActionResultUnion? = null,

    @SerialName(value = "leave_action_result")
    val leaveActionResult: CommunityLeaveActionResult? = null,

    @SerialName(value = "pin_action_result")
    val pinActionResult: CommunityPinActionResult? = null,

    @SerialName(value = "unpin_action_result")
    val unpinActionResult: CommunityUnpinActionResult? = null

) {


}

