/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.CommunityActions
import dev.dimension.flare.data.network.xqt.model.CommunityInvitesResult
import dev.dimension.flare.data.network.xqt.model.CommunityJoinRequestsResult
import dev.dimension.flare.data.network.xqt.model.CommunityRule
import dev.dimension.flare.data.network.xqt.model.CommunityUrls
import dev.dimension.flare.data.network.xqt.model.PrimaryCommunityTopic
import dev.dimension.flare.data.network.xqt.model.TypeName
import dev.dimension.flare.data.network.xqt.model.UserResults

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param actions 
 * @param adminResults 
 * @param createdAt 
 * @param creatorResults 
 * @param customBannerMedia 
 * @param defaultBannerMedia 
 * @param description 
 * @param idStr 
 * @param invitesPolicy 
 * @param invitesResult 
 * @param isPinned 
 * @param joinPolicy 
 * @param joinRequestsResult 
 * @param memberCount 
 * @param membersFacepileResults 
 * @param moderatorCount 
 * @param name 
 * @param primaryCommunityTopic 
 * @param question 
 * @param role 
 * @param rules 
 * @param searchTags 
 * @param showOnlyUsersToDisplay 
 * @param urls 
 * @param viewerRelationship 
 */
@Serializable
@SerialName("Community")

internal data class Community (

@SerialName(value = "actions")
    val actions: CommunityActions? = null,

@SerialName(value = "admin_results")
    val adminResults: UserResults? = null,

@SerialName(value = "created_at")
    val createdAt: kotlin.Int? = null,

@SerialName(value = "creator_results")
    val creatorResults: UserResults? = null,

@Contextual @SerialName(value = "custom_banner_media")
    val customBannerMedia: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

@Contextual @SerialName(value = "default_banner_media")
    val defaultBannerMedia: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

@SerialName(value = "description")
    val description: kotlin.String? = null,

@SerialName(value = "id_str")
    val idStr: kotlin.String? = null,

@SerialName(value = "invites_policy")
    val invitesPolicy: Community.InvitesPolicy? = null,

@SerialName(value = "invites_result")
    val invitesResult: CommunityInvitesResult? = null,

@SerialName(value = "is_pinned")
    val isPinned: kotlin.Boolean? = null,

@SerialName(value = "join_policy")
    val joinPolicy: Community.JoinPolicy? = null,

@SerialName(value = "join_requests_result")
    val joinRequestsResult: CommunityJoinRequestsResult? = null,

@SerialName(value = "member_count")
    val memberCount: kotlin.Int? = null,

@SerialName(value = "members_facepile_results")
    val membersFacepileResults: kotlin.collections.List<UserResults>? = null,

@SerialName(value = "moderator_count")
    val moderatorCount: kotlin.Int? = null,

@SerialName(value = "name")
    val name: kotlin.String? = null,

@SerialName(value = "primary_community_topic")
    val primaryCommunityTopic: PrimaryCommunityTopic? = null,

@SerialName(value = "question")
    val question: kotlin.String? = null,

@SerialName(value = "role")
    val role: Community.Role? = null,

@SerialName(value = "rules")
    val rules: kotlin.collections.List<CommunityRule>? = null,

@SerialName(value = "search_tags")
    val searchTags: kotlin.collections.List<kotlin.String>? = null,

@SerialName(value = "show_only_users_to_display")
    val showOnlyUsersToDisplay: kotlin.collections.List<kotlin.String>? = null,

@SerialName(value = "urls")
    val urls: CommunityUrls? = null,

@Contextual @SerialName(value = "viewer_relationship")
    val viewerRelationship: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null

) : CommunityUnion {

    /**
     * 
     *
     * Values: MemberInvitesAllowed,ModeratorInvitesAllowed
     */
    @Serializable
    internal enum class InvitesPolicy(val value: kotlin.String) {
        @SerialName(value = "MemberInvitesAllowed") MemberInvitesAllowed("MemberInvitesAllowed"),
        @SerialName(value = "ModeratorInvitesAllowed") ModeratorInvitesAllowed("ModeratorInvitesAllowed");
    }
    /**
     * 
     *
     * Values: Open,RestrictedJoinRequestsRequireModeratorApproval
     */
    @Serializable
    internal enum class JoinPolicy(val value: kotlin.String) {
        @SerialName(value = "Open") Open("Open"),
        @SerialName(value = "RestrictedJoinRequestsRequireModeratorApproval") RestrictedJoinRequestsRequireModeratorApproval("RestrictedJoinRequestsRequireModeratorApproval");
    }
    /**
     * 
     *
     * Values: NonMember
     */
    @Serializable
    internal enum class Role(val value: kotlin.String) {
        @SerialName(value = "NonMember") NonMember("NonMember");
    }

}

