/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.TypeName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param reason 
 */
@Serializable

internal data class CommunityDeleteActionResult (

    @Contextual @SerialName(value = "__typename")
    val typename: TypeName,

    @SerialName(value = "reason")
    val reason: CommunityDeleteActionResult.Reason

) {

    /**
     * 
     *
     * Values: Unavailable
     */
    @Serializable
    internal enum class Reason(val value: kotlin.String) {
        @SerialName(value = "Unavailable") Unavailable("Unavailable");
    }

}

