/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ContentDisclosureAdvertisingDisclosure
import dev.dimension.flare.data.network.xqt.model.ContentDisclosureAiGeneratedDisclosure

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param advertisingDisclosure 
 * @param aiGeneratedDisclosure 
 */
@Serializable

internal data class ContentDisclosure (

    @SerialName(value = "advertising_disclosure")
    val advertisingDisclosure: ContentDisclosureAdvertisingDisclosure? = null,

    @SerialName(value = "ai_generated_disclosure")
    val aiGeneratedDisclosure: ContentDisclosureAiGeneratedDisclosure? = null

) {


}

