/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMConversationSearchTabGroupsQueryResponseData
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param `data`
 */
@Serializable
internal data class DMConversationSearchTabGroupsQueryResponse(
    @SerialName(value = "data")
    val `data`: DMConversationSearchTabGroupsQueryResponseData? = null,
)
