/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param errors
 */
@Serializable
internal data class ErrorResponse(
    @SerialName(value = "errors")
    val errors: Errors,
    @SerialName(value = "code")
    val code: kotlin.Int? = null,
    @SerialName(value = "extensions")
    val extensions: ErrorExtensions? = null,
    @SerialName(value = "kind")
    val kind: kotlin.String? = null,
    @SerialName(value = "locations")
    val locations: kotlin.collections.List<Location>? = null,
    @SerialName(value = "message")
    val message: kotlin.String? = null,
    @SerialName(value = "name")
    val name: kotlin.String? = null,
    @SerialName(value = "path")
    val path: kotlin.collections.List<ErrorResponsePathInner>? = null,
    @SerialName(value = "source")
    val source: kotlin.String? = null,
    @SerialName(value = "tracing")
    val tracing: Tracing? = null,
    @SerialName(value = "retry_after")
    val retryAfter: kotlin.Int? = null,
)
