/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.GrokEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param destinationLanguage 
 * @param sourceLanguage 
 * @param translation 
 * @param translationAvailable 
 * @param richTextEntities 
 */
@Serializable

internal data class GrokTranslatedCommunityNote (

    @SerialName(value = "destination_language")
    val destinationLanguage: kotlin.String,

    @SerialName(value = "source_language")
    val sourceLanguage: kotlin.String,

    @SerialName(value = "translation")
    val translation: kotlin.String,

    @SerialName(value = "translation_available")
    val translationAvailable: kotlin.Boolean,

    @SerialName(value = "rich_text_entities")
    val richTextEntities: kotlin.collections.List<GrokEntity>? = null

) {


}

