/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaColorR
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param r
 * @param ttl
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaColor(
    @SerialName(value = "r")
    val r: InboxConversationTimelineMessageDataAttachmentMediaColorR? = null,
    @SerialName(value = "ttl")
    val ttl: kotlin.Int? = null,
)
