/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param red
 * @param green
 * @param blue
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaRGB(
    @SerialName(value = "red")
    val red: kotlin.Int? = null,
    @SerialName(value = "green")
    val green: kotlin.Int? = null,
    @SerialName(value = "blue")
    val blue: kotlin.Int? = null,
)
