/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param url
 * @param width
 * @param height
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaOriginalInfo(
    @SerialName(value = "url")
    val url: kotlin.String? = null,
    @SerialName(value = "width")
    val width: kotlin.Double? = null,
    @SerialName(value = "height")
    val height: kotlin.Double? = null,
)
