/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param height
 * @param width
 * @param focusRects
 */
@Serializable
internal data class MediaOriginalInfo(
    @SerialName(value = "height")
    val height: kotlin.Int,
    @SerialName(value = "width")
    val width: kotlin.Int,
    @SerialName(value = "focus_rects")
    val focusRects: kotlin.collections.List<MediaOriginalInfoFocusRect>? = null,
)
