/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.TweetInterstitialText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param opacity 
 * @param text 
 * @param title 
 */
@Serializable

internal data class MediaVisibilityResultsBlurredImageInterstitial (

    @Contextual @SerialName(value = "opacity")
    val opacity: kotlin.Double,

    @SerialName(value = "text")
    val text: TweetInterstitialText,

    @SerialName(value = "title")
    val title: TweetInterstitialText

) {


}

