/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param darkRequest
 * @param media
 * @param semanticAnnotationIds
 * @param tweetText
 * @param reply
 */
@Serializable
internal data class PostCreateTweetRequestVariables(
    @SerialName(value = "dark_request")
    val darkRequest: kotlin.Boolean = false,
    @SerialName(value = "media")
    val media: PostCreateTweetRequestVariablesMedia,
    @SerialName(value = "semantic_annotation_ids")
    val semanticAnnotationIds: kotlin.collections.List<@Contextual kotlin.Any>,
    @SerialName(value = "tweet_text")
    val tweetText: kotlin.String = "test",
    @SerialName(value = "reply")
    val reply: PostCreateTweetRequestVariablesReply? = null,
    @SerialName(value = "attachment_url")
    val attachmentUrl: kotlin.String? = null,
    @SerialName(value = "conversation_control")
    val conversationControl: PostCreateTweetRequestVariablesConversationControl? = null,
)

@Serializable
internal data class PostCreateTweetRequestVariablesConversationControl(
    @SerialName(value = "value")
    val mode: Mode,
) {
    @Serializable
    enum class Mode {
        ByInvitation,
        Verified,
        Community,
    }
}

@Serializable
internal data class PostMediaMetadataCreateRequest(
    @SerialName("media_id")
    val mediaId: String,
    // other, graphic_violence, adult_content
    @SerialName("sensitive_media_warning")
    val sensitiveMediaWarning: List<SensitiveMediaWarning>? = null,
    @SerialName("alt_text")
    val altText: AltText? = null,
) {
    @Serializable
    enum class SensitiveMediaWarning {
        @SerialName("other")
        Other,

        @SerialName("graphic_violence")
        GraphicViolence,

        @SerialName("adult_content")
        AdultContent,
    }

    @Serializable
    data class AltText(
        @SerialName("text")
        val text: String,
    )
}
