/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param freedomOfSpeechNotReachFetchEnabled
 * @param graphqlIsTranslatableRwebTweetIsTranslatableEnabled
 * @param longformNotetweetsConsumptionEnabled
 * @param longformNotetweetsInlineMediaEnabled
 * @param longformNotetweetsRichTextReadEnabled
 * @param responsiveWebEditTweetApiEnabled
 * @param responsiveWebEnhanceCardsEnabled
 * @param responsiveWebGraphqlExcludeDirectiveEnabled
 * @param responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled
 * @param responsiveWebGraphqlTimelineNavigationEnabled
 * @param responsiveWebMediaDownloadVideoEnabled
 * @param responsiveWebTwitterArticleTweetConsumptionEnabled
 * @param standardizedNudgesMisinfo
 * @param tweetAwardsWebTippingEnabled
 * @param tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled
 * @param tweetypieUnmentionOptimizationEnabled
 * @param verifiedPhoneLabelEnabled
 * @param viewCountsEverywhereApiEnabled
 */
@Serializable
internal data class PostCreateTweetRequestFeatures(
    @Required
    @SerialName(value = "freedom_of_speech_not_reach_fetch_enabled")
    val freedomOfSpeechNotReachFetchEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "graphql_is_translatable_rweb_tweet_is_translatable_enabled")
    val graphqlIsTranslatableRwebTweetIsTranslatableEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "longform_notetweets_consumption_enabled")
    val longformNotetweetsConsumptionEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "longform_notetweets_inline_media_enabled")
    val longformNotetweetsInlineMediaEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "longform_notetweets_rich_text_read_enabled")
    val longformNotetweetsRichTextReadEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "responsive_web_edit_tweet_api_enabled")
    val responsiveWebEditTweetApiEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "responsive_web_enhance_cards_enabled")
    val responsiveWebEnhanceCardsEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "responsive_web_graphql_exclude_directive_enabled")
    val responsiveWebGraphqlExcludeDirectiveEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "responsive_web_graphql_skip_user_profile_image_extensions_enabled")
    val responsiveWebGraphqlSkipUserProfileImageExtensionsEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "responsive_web_graphql_timeline_navigation_enabled")
    val responsiveWebGraphqlTimelineNavigationEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "responsive_web_media_download_video_enabled")
    val responsiveWebMediaDownloadVideoEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "responsive_web_twitter_article_tweet_consumption_enabled")
    val responsiveWebTwitterArticleTweetConsumptionEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "standardized_nudges_misinfo")
    val standardizedNudgesMisinfo: kotlin.Boolean = true,
    @Required
    @SerialName(value = "tweet_awards_web_tipping_enabled")
    val tweetAwardsWebTippingEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled")
    val tweetWithVisibilityResultsPreferGqlLimitedActionsPolicyEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "tweetypie_unmention_optimization_enabled")
    val tweetypieUnmentionOptimizationEnabled: kotlin.Boolean = true,
    @Required
    @SerialName(value = "verified_phone_label_enabled")
    val verifiedPhoneLabelEnabled: kotlin.Boolean = false,
    @Required
    @SerialName(value = "view_counts_everywhere_api_enabled")
    val viewCountsEverywhereApiEnabled: kotlin.Boolean = true,
    @SerialName(value = "articles_preview_enabled")
    val articlesPreviewEnabled: kotlin.Boolean = true,
    @SerialName(value = "c9s_tweet_anatomy_moderator_badge_enabled")
    val c9sTweetAnatomyModeratorBadgeEnabled: kotlin.Boolean = true,
    @SerialName(value = "communities_web_enable_tweet_community_results_fetch")
    val communitiesWebEnableTweetCommunityResultsFetch: kotlin.Boolean = true,
    @SerialName(value = "content_disclosure_ai_generated_indicator_enabled")
    val contentDisclosureAiGeneratedIndicatorEnabled: kotlin.Boolean = true,
    @SerialName(value = "content_disclosure_indicator_enabled")
    val contentDisclosureIndicatorEnabled: kotlin.Boolean = true,
    @SerialName(value = "post_ctas_fetch_enabled")
    val postCtasFetchEnabled: kotlin.Boolean = true,
    @SerialName(value = "premium_content_api_read_enabled")
    val premiumContentApiReadEnabled: kotlin.Boolean = false,
    @SerialName(value = "profile_label_improvements_pcf_label_in_post_enabled")
    val profileLabelImprovementsPcfLabelInPostEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_analysis_button_from_backend")
    val responsiveWebGrokAnalysisButtonFromBackend: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_analyze_button_fetch_trends_enabled")
    val responsiveWebGrokAnalyzeButtonFetchTrendsEnabled: kotlin.Boolean = false,
    @SerialName(value = "responsive_web_grok_analyze_post_followups_enabled")
    val responsiveWebGrokAnalyzePostFollowupsEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_annotations_enabled")
    val responsiveWebGrokAnnotationsEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_community_note_auto_translation_is_enabled")
    val responsiveWebGrokCommunityNoteAutoTranslationIsEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_image_annotation_enabled")
    val responsiveWebGrokImageAnnotationEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_imagine_annotation_enabled")
    val responsiveWebGrokImagineAnnotationEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_share_attachment_enabled")
    val responsiveWebGrokShareAttachmentEnabled: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_grok_show_grok_translated_post")
    val responsiveWebGrokShowGrokTranslatedPost: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_jetfuel_frame")
    val responsiveWebJetfuelFrame: kotlin.Boolean = true,
    @SerialName(value = "responsive_web_profile_redirect_enabled")
    val responsiveWebProfileRedirectEnabled: kotlin.Boolean = false,
    @SerialName(value = "rweb_cashtags_composer_attachment_enabled")
    val rwebCashtagsComposerAttachmentEnabled: kotlin.Boolean = true,
    @SerialName(value = "rweb_cashtags_enabled")
    val rwebCashtagsEnabled: kotlin.Boolean = true,
    @SerialName(value = "rweb_conversational_replies_downvote_enabled")
    val rwebConversationalRepliesDownvoteEnabled: kotlin.Boolean = false,
    @SerialName(value = "rweb_tipjar_consumption_enabled")
    val rwebTipjarConsumptionEnabled: kotlin.Boolean = false,
)
