/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param excludeReplyUserIds
 * @param inReplyToTweetId
 */
@Serializable
internal data class PostCreateTweetRequestVariablesReply(
    @SerialName(value = "exclude_reply_user_ids")
    val excludeReplyUserIds: kotlin.collections.List<@Contextual kotlin.Any>,
    @SerialName(value = "in_reply_to_tweet_id")
    val inReplyToTweetId: kotlin.String = "1111111111111111111",
)
