/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.PostCtaTitleText

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param actionUrl 
 * @param backgroundColor 
 * @param showChevron 
 * @param strokeColor 
 * @param titleText 
 */
@Serializable

internal data class PostCta (

    @Contextual @SerialName(value = "action_url")
    val actionUrl: kotlin.String,

    @SerialName(value = "background_color")
    val backgroundColor: kotlin.String,

    @SerialName(value = "show_chevron")
    val showChevron: kotlin.Boolean,

    @SerialName(value = "stroke_color")
    val strokeColor: kotlin.String,

    @SerialName(value = "title_text")
    val titleText: PostCtaTitleText

) {


}

