/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param adultContent 
 * @param graphicViolence 
 * @param other 
 */
@Serializable

internal data class SensitiveMediaWarning (

    @SerialName(value = "adult_content")
    val adultContent: kotlin.Boolean? = null,

    @SerialName(value = "graphic_violence")
    val graphicViolence: kotlin.Boolean? = null,

    @SerialName(value = "other")
    val other: kotlin.Boolean? = null

) {


}

