/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.UrtEndpointOptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param urlType 
 * @param urtEndpointOptions 
 */
@Serializable

internal data class SocialContextLandingUrl (

    @Contextual @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "urlType")
    val urlType: SocialContextLandingUrl.UrlType? = null,

    @SerialName(value = "urtEndpointOptions")
    val urtEndpointOptions: UrtEndpointOptions? = null

) {

    /**
     * 
     *
     * Values: DeepLink,UrtEndpoint,ExternalUrl
     */
    @Serializable
    internal enum class UrlType(val value: kotlin.String) {
        @SerialName(value = "DeepLink") DeepLink("DeepLink"),
        @SerialName(value = "UrtEndpoint") UrtEndpoint("UrtEndpoint"),
        @SerialName(value = "ExternalUrl") ExternalUrl("ExternalUrl");
    }

}

