/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param originalImgHeight 
 * @param originalImgUrl 
 * @param originalImgWidth 
 */
@Serializable

internal data class ThumbnailImage (

    @SerialName(value = "original_img_height")
    val originalImgHeight: kotlin.Int? = null,

    @Contextual @SerialName(value = "original_img_url")
    val originalImgUrl: kotlin.String? = null,

    @SerialName(value = "original_img_width")
    val originalImgWidth: kotlin.Int? = null

) {


}

