/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ContentItemType
import dev.dimension.flare.data.network.xqt.model.TombstoneInfo
import dev.dimension.flare.data.network.xqt.model.TypeName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param itemType 
 * @param tombstoneDisplayType 
 * @param tombstoneInfo 
 */
@Serializable
@SerialName("TimelineTombstone")

internal data class TimelineTombstone (

@Contextual @SerialName(value = "itemType")
    val itemType: ContentItemType? = null,

@SerialName(value = "tombstoneDisplayType")
    val tombstoneDisplayType: TimelineTombstone.TombstoneDisplayType? = null,

@SerialName(value = "tombstoneInfo")
    val tombstoneInfo: TombstoneInfo? = null

) : ItemContentUnion {

    /**
     * 
     *
     * Values: Inline
     */
    @Serializable
    internal enum class TombstoneDisplayType(val value: kotlin.String) {
        @SerialName(value = "Inline") Inline("Inline");
    }

}

