/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ContentItemType
import dev.dimension.flare.data.network.xqt.model.SocialContextLandingUrl
import dev.dimension.flare.data.network.xqt.model.SocialContextUnion
import dev.dimension.flare.data.network.xqt.model.ThumbnailImage
import dev.dimension.flare.data.network.xqt.model.TrendImage
import dev.dimension.flare.data.network.xqt.model.TrendMetadata
import dev.dimension.flare.data.network.xqt.model.TypeName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param name 
 * @param trendMetadata 
 * @param trendUrl 
 * @param images 
 * @param isAiTrend 
 * @param itemType 
 * @param socialContext 
 * @param thumbnailImage 
 */
@Serializable
@SerialName("TimelineTrend")

internal data class TimelineTrend (

@SerialName(value = "name")
    val name: kotlin.String,

@SerialName(value = "trend_metadata")
    val trendMetadata: TrendMetadata,

@SerialName(value = "trend_url")
    val trendUrl: SocialContextLandingUrl,

@SerialName(value = "images")
    val images: kotlin.collections.List<TrendImage>? = null,

@SerialName(value = "is_ai_trend")
    val isAiTrend: kotlin.Boolean? = null,

@Contextual @SerialName(value = "itemType")
    val itemType: ContentItemType? = null,

@SerialName(value = "social_context")
    val socialContext: SocialContextUnion? = null,

@SerialName(value = "thumbnail_image")
    val thumbnailImage: ThumbnailImage? = null

) : ItemContentUnion {


}

