/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ContentItemType
import dev.dimension.flare.data.network.xqt.model.NotificationTemplate
import dev.dimension.flare.data.network.xqt.model.RichMessage
import dev.dimension.flare.data.network.xqt.model.SocialContextLandingUrl
import dev.dimension.flare.data.network.xqt.model.TypeName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param id 
 * @param itemType 
 * @param notificationIcon 
 * @param notificationUrl 
 * @param richMessage 
 * @param template 
 * @param timestampMs 
 */
@Serializable
@SerialName("TimelineNotification")

internal data class TimelineNotification (

@SerialName(value = "id")
    val id: kotlin.String,

@Contextual @SerialName(value = "itemType")
    val itemType: ContentItemType,

@SerialName(value = "notification_icon")
    val notificationIcon: kotlin.String,

@SerialName(value = "notification_url")
    val notificationUrl: SocialContextLandingUrl,

@SerialName(value = "rich_message")
    val richMessage: RichMessage,

@SerialName(value = "template")
    val template: NotificationTemplate,

@SerialName(value = "timestamp_ms")
    val timestampMs: kotlin.String

) : ItemContentUnion {


}

