/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param urlType 
 */
@Serializable

internal data class TimelineCoverBehaviorUrl (

    @Contextual @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "url_type")
    val urlType: TimelineCoverBehaviorUrl.UrlType

) {

    /**
     * 
     *
     * Values: ExternalUrl
     */
    @Serializable
    internal enum class UrlType(val value: kotlin.String) {
        @SerialName(value = "ExternalUrl") ExternalUrl("ExternalUrl");
    }

}

