/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.SocialContextUnionType
import dev.dimension.flare.data.network.xqt.model.TopicContext

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param functionalityType 
 * @param topic 
 * @param type 
 */
@Serializable
@SerialName("TimelineTopicContext")

internal data class TimelineTopicContext (

@SerialName(value = "functionalityType")
    val functionalityType: TimelineTopicContext.FunctionalityType? = null,

@SerialName(value = "topic")
    val topic: TopicContext? = null

) : SocialContextUnion {

    /**
     * 
     *
     * Values: Basic
     */
    @Serializable
    internal enum class FunctionalityType(val value: kotlin.String) {
        @SerialName(value = "Basic") Basic("Basic");
    }

}

