/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param following 
 * @param iconUrl 
 * @param id 
 * @param name 
 * @param notInterested 
 * @param topicId 
 */
@Serializable

internal data class TopicContext (

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "following")
    val following: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "icon_url")
    val iconUrl: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "not_interested")
    val notInterested: kotlin.Boolean? = null,

    @SerialName(value = "topic_id")
    val topicId: kotlin.String? = null

) {


}

