/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param type
 * @param booleanValue
 * @param scribeKey
 * @param stringValue
 */
@Serializable
internal data class TweetCardLegacyBindingValueData(
    @SerialName(value = "type")
    val type: kotlin.String,
    @SerialName(value = "boolean_value")
    val booleanValue: kotlin.Boolean? = null,
    @SerialName(value = "scribe_key")
    val scribeKey: kotlin.String? = null,
    @SerialName(value = "string_value")
    val stringValue: kotlin.String? = null,
    @SerialName(value = "image_value")
    val imageValue: ImageValue? = null,
    @SerialName(value = "image_color_value")
    val imageColorValue: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,
    @SerialName(value = "user_value")
    val userValue: UserValue? = null,
)

@Serializable
internal data class ImageValue(
    val height: Long? = null,
    val width: Long? = null,
    val url: String? = null,
)
