/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.TweetInterstitialRevealText
import dev.dimension.flare.data.network.xqt.model.TweetInterstitialText
import dev.dimension.flare.data.network.xqt.model.TypeName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param displayType 
 * @param revealText 
 * @param text 
 */
@Serializable

internal data class TweetInterstitial (

    @Contextual @SerialName(value = "__typename")
    val typename: TypeName,

    @SerialName(value = "displayType")
    val displayType: TweetInterstitial.DisplayType,

    @SerialName(value = "revealText")
    val revealText: TweetInterstitialRevealText,

    @SerialName(value = "text")
    val text: TweetInterstitialText

) {

    /**
     * 
     *
     * Values: NonCompliant,EntireTweet
     */
    @Serializable
    internal enum class DisplayType(val value: kotlin.String) {
        @SerialName(value = "NonCompliant") NonCompliant("NonCompliant"),
        @SerialName(value = "EntireTweet") EntireTweet("EntireTweet");
    }

}

