/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.ArticlePreview
import dev.dimension.flare.data.network.xqt.model.TweetPreviewDisplayTweetViewCount
import dev.dimension.flare.data.network.xqt.model.UserResultCore

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bookmarkCount 
 * @param core 
 * @param createdAt 
 * @param entities 
 * @param favoriteCount 
 * @param quoteCount 
 * @param replyCount 
 * @param restId 
 * @param retweetCount 
 * @param text 
 * @param viewCount 
 * @param articlePreview 
 */
@Serializable

internal data class TweetPreviewDisplayTweet (

    @SerialName(value = "bookmark_count")
    val bookmarkCount: kotlin.Int,

    @SerialName(value = "core")
    val core: UserResultCore,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @Contextual @SerialName(value = "entities")
    val entities: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "favorite_count")
    val favoriteCount: kotlin.Int,

    @SerialName(value = "quote_count")
    val quoteCount: kotlin.Int,

    @SerialName(value = "reply_count")
    val replyCount: kotlin.Int,

    @SerialName(value = "rest_id")
    val restId: kotlin.String,

    @SerialName(value = "retweet_count")
    val retweetCount: kotlin.Int,

    @SerialName(value = "text")
    val text: kotlin.String,

    @SerialName(value = "view_count")
    val viewCount: TweetPreviewDisplayTweetViewCount,

    @SerialName(value = "article_preview")
    val articlePreview: ArticlePreview? = null

) {


}

