/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param editControl
 * @param isTranslatable
 * @param restId
 * @param views
 * @param typename
 * @param birdwatchPivot
 * @param card
 * @param core
 * @param editPrespective
 * @param legacy
 * @param noteTweet
 * @param quickPromoteEligibility
 * @param quotedStatusResult
 * @param source
 * @param unmentionData
 */
@Serializable
@SerialName("Tweet")
internal data class Tweet(
//    @SerialName(value = "edit_control")
//    val editControl: TweetEditControl,
//    @SerialName(value = "is_translatable")
//    val isTranslatable: kotlin.Boolean = false,
    @SerialName(value = "rest_id")
    val restId: kotlin.String,
//    @SerialName(value = "views")
//    val views: TweetView,
//    @Contextual @SerialName(value = "__typename")
//    val typename: TypeName? = null,
//    @SerialName(value = "birdwatch_pivot")
//    val birdwatchPivot: BirdwatchPivot? = null,
    @SerialName(value = "card")
    val card: TweetCard? = null,
    @SerialName(value = "core")
    val core: UserResultCore? = null,
//    @SerialName(value = "edit_prespective")
//    val editPrespective: TweetEditPrespective? = null,
    @SerialName(value = "article")
    val article: TwitterArticle? = null,
    @SerialName(value = "legacy")
    val legacy: TweetLegacy? = null,
    @SerialName(value = "note_tweet")
    val noteTweet: NoteTweet? = null,
//    @Contextual @SerialName(value = "quick_promote_eligibility")
//    val quickPromoteEligibility: kotlin.Any? = null,
    @SerialName(value = "quoted_status_result")
    val quotedStatusResult: ItemResult? = null,
    @SerialName(value = "source")
    val source: kotlin.String? = null,
//    @Contextual @SerialName(value = "unmention_data")
//    val unmentionData: JsonElement? = null,
    @SerialName(value = "author_community_relationship")
    val authorCommunityRelationship: AuthorCommunityRelationship? = null,
    @SerialName(value = "community_relationship")
    val communityRelationship: CommunityRelationship? = null,
    @SerialName(value = "community_results")
    val communityResults: CommunityResult? = null,
    @SerialName(value = "content_disclosure")
    val contentDisclosure: ContentDisclosure? = null,
    @SerialName(value = "grok_analysis_button")
    val grokAnalysisButton: kotlin.Boolean? = null,
    @SerialName(value = "grok_analysis_followups")
    val grokAnalysisFollowups: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "grok_annotations")
    val grokAnnotations: GrokAnnotation? = null,
    @SerialName(value = "grok_share_attachment")
    val grokShareAttachment: GrokShareAttachment? = null,
    @SerialName(value = "grok_translated_post_with_availability")
    val grokTranslatedPostWithAvailability: GrokTranslatedPostWithAvailability? = null,
    @SerialName(value = "has_birdwatch_notes")
    val hasBirdwatchNotes: kotlin.Boolean? = null,
    @SerialName(value = "postCta")
    val postCta: TweetPostCta? = null,
    @SerialName(value = "post_image_description")
    val postImageDescription: kotlin.String? = null,
    @SerialName(value = "post_video_description")
    val postVideoDescription: kotlin.String? = null,
    @SerialName(value = "previous_counts")
    val previousCounts: TweetPreviousCounts? = null,
    @SerialName(value = "quotedRefResult")
    val quotedRefResult: QuotedRefResult? = null,
    @SerialName(value = "superFollowsReplyUserResult")
    val superFollowsReplyUserResult: SuperFollowsReplyUserResult? = null,
    @SerialName(value = "trend_results")
    val trendResults: TrendResults? = null,
    @SerialName(value = "unified_card")
    val unifiedCard: UnifiedCard? = null,
) : TweetUnion
