/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param verified 
 * @param verifiedType 
 */
@Serializable

internal data class UserVerification (

    @SerialName(value = "verified")
    val verified: kotlin.Boolean,

    @SerialName(value = "verified_type")
    val verifiedType: UserVerification.VerifiedType? = null

) {

    /**
     * 
     *
     * Values: Business,Government
     */
    @Serializable
    internal enum class VerifiedType(val value: kotlin.String) {
        @SerialName(value = "Business") Business("Business"),
        @SerialName(value = "Government") Government("Government");
    }

}

