/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockedBy 
 * @param blocking 
 * @param followedBy 
 * @param following 
 */
@Serializable

internal data class UserRelationshipPerspectives (

    @SerialName(value = "blocked_by")
    val blockedBy: kotlin.Boolean? = null,

    @SerialName(value = "blocking")
    val blocking: kotlin.Boolean? = null,

    @SerialName(value = "followed_by")
    val followedBy: kotlin.Boolean? = null,

    @SerialName(value = "following")
    val following: kotlin.Boolean? = null

) {


}

