/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.UserVerificationInfoReasonDescription

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param verifiedSinceMsec 
 * @param overrideVerifiedYear 
 */
@Serializable

internal data class UserVerificationInfoReason (

    @SerialName(value = "description")
    val description: UserVerificationInfoReasonDescription,

    @SerialName(value = "verified_since_msec")
    val verifiedSinceMsec: kotlin.String,

    @SerialName(value = "override_verified_year")
    val overrideVerifiedYear: kotlin.Int? = null

) {


}

