/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bandcampHandle 
 * @param bitcoinHandle 
 * @param cashAppHandle 
 * @param ethereumHandle 
 * @param gofundmeHandle 
 * @param isEnabled 
 * @param patreonHandle 
 * @param payPalHandle 
 * @param venmoHandle 
 */
@Serializable

internal data class UserTipJarSettings (

    @SerialName(value = "bandcamp_handle")
    val bandcampHandle: kotlin.String? = null,

    @SerialName(value = "bitcoin_handle")
    val bitcoinHandle: kotlin.String? = null,

    @SerialName(value = "cash_app_handle")
    val cashAppHandle: kotlin.String? = null,

    @SerialName(value = "ethereum_handle")
    val ethereumHandle: kotlin.String? = null,

    @SerialName(value = "gofundme_handle")
    val gofundmeHandle: kotlin.String? = null,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @SerialName(value = "patreon_handle")
    val patreonHandle: kotlin.String? = null,

    @SerialName(value = "pay_pal_handle")
    val payPalHandle: kotlin.String? = null,

    @SerialName(value = "venmo_handle")
    val venmoHandle: kotlin.String? = null

) {


}

