/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typename
 * @param id
 * @param legacy
// * @param profilemodules
 * @param restId
 */
@Serializable
internal data class UserResultByScreenNameResult(
    @Contextual @SerialName(value = "__typename")
    val typename: TypeName,
    @SerialName(value = "id")
    val id: kotlin.String,
    @SerialName(value = "legacy")
    val legacy: UserResultByScreenNameLegacy? = null,
//    @Contextual @SerialName(value = "profilemodules")
//    val profilemodules: JsonElement,
    @SerialName(value = "rest_id")
    val restId: kotlin.String,
    @SerialName(value = "core")
    val core: UserResultByScreenNameCore? = null,
    @SerialName(value = "privacy")
    val privacy: UserResultPrivacy? = null,
    @SerialName(value = "relationship_perspectives")
    val relationshipPerspectives: UserResultRelationshipPerspectives? = null,
)
