/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param capacity * @param usage */
@Serializable
internal data class Drive200Response(
    @SerialName(value = "capacity") val capacity: kotlin.Double,
    @SerialName(value = "usage") val usage: kotlin.Double,
)
