/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * Values: top,bottom,showMore,showMoreThreads,gap
 */
@Serializable
enum class CursorType(val value: kotlin.String) {
    @SerialName(value = "Top")
    top("Top"),

    @SerialName(value = "Bottom")
    bottom("Bottom"),

    @SerialName(value = "ShowMore")
    showMore("ShowMore"),

    @SerialName(value = "ShowMoreThreads")
    showMoreThreads("ShowMoreThreads"),

    @SerialName(value = "Gap")
    gap("Gap"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CursorType) "$data" else null

        /**
         * Returns a valid [CursorType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CursorType? =
            data?.let {
                val normalizedData = "$it".lowercase()
                values().firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
