/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typename 
 * @param restId 
 * @param id 
 */
@Serializable

internal data class DMAddParticipantsMutationResponseDataAddParticipantsParticipantsJoinEventDmEventResultsResult (

    @SerialName(value = "__typename")
    val typename: kotlin.String? = null,

    @SerialName(value = "rest_id")
    val restId: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null

) {


}

