/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMBlockUserResponseDataDmBlockByRestId

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dmBlockByRestId 
 */
@Serializable

internal data class DMBlockUserResponseData (

    @SerialName(value = "dm_block_by_rest_id")
    val dmBlockByRestId: DMBlockUserResponseDataDmBlockByRestId? = null

) {


}

