/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMPeopleSearchSlice
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param dmPeopleConvoSliceResult
 */
@Serializable
internal data class DMConversationSearchTabPeopleQueryResponseData(
    @SerialName(value = "dm_people_convo_slice_result")
    val dmPeopleConvoSliceResult: DMPeopleSearchSlice? = null,
)
