/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMEventDetailDM
import dev.dimension.flare.data.network.xqt.model.DMEventDetailInitialLowQualityState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param initialLowQualityState 
 * @param markedAsAbuse 
 * @param messageId 
 * @param dm 
 */
@Serializable

internal data class DMEventDetail (

    @SerialName(value = "initial_low_quality_state")
    val initialLowQualityState: DMEventDetailInitialLowQualityState? = null,

    @SerialName(value = "marked_as_abuse")
    val markedAsAbuse: kotlin.Boolean? = null,

    @SerialName(value = "message_id")
    val messageId: kotlin.String? = null,

    @SerialName(value = "dm")
    val dm: DMEventDetailDM? = null

) {


}

