/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMEventDetailDMEntities
import dev.dimension.flare.data.network.xqt.model.DMUserResults

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAtSec 
 * @param id 
 * @param text 
 * @param entities 
 * @param attachments 
 * @param recipientResults 
 * @param senderResults 
 */
@Serializable

internal data class DMEventDetailDM (

    @SerialName(value = "created_at_sec")
    val createdAtSec: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "text")
    val text: kotlin.String? = null,

    @SerialName(value = "entities")
    val entities: DMEventDetailDMEntities? = null,

    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<@Contextual kotlin.Any>? = null,

    @SerialName(value = "recipient_results")
    val recipientResults: DMUserResults? = null,

    @SerialName(value = "sender_results")
    val senderResults: DMUserResults? = null

) {


}

