/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMGroupSearchSliceItemsInner
import dev.dimension.flare.data.network.xqt.model.DMGroupSearchSliceSliceInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sliceInfo 
 * @param items 
 */
@Serializable

internal data class DMGroupSearchSlice (

    @SerialName(value = "sliceInfo")
    val sliceInfo: DMGroupSearchSliceSliceInfo? = null,

    @SerialName(value = "items")
    val items: kotlin.collections.List<DMGroupSearchSliceItemsInner>? = null

) {


}

