/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMInboxPinnedConversationUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param result 
 * @param id 
 */
@Serializable

internal data class DMInboxPinnedConversationParticipantUserResults (

    @SerialName(value = "result")
    val result: DMInboxPinnedConversationUser? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null

) {


}

