/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param labelType
 * @param timestamp
 */
@Serializable
internal data class DMInboxPinnedConversationLabel(
    @SerialName(value = "label_type")
    val labelType: kotlin.String? = null,
    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long? = null,
)
