/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param conversationId 
 * @param conversationType 
 */
@Serializable

internal data class DMInboxPinnedConversationLegacyMetadata (

    @SerialName(value = "conversation_id")
    val conversationId: kotlin.String? = null,

    @SerialName(value = "conversation_type")
    val conversationType: kotlin.String? = null

) {


}

