/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMInboxPinnedInboxQueryResponseDataLabeledConversationSlice

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param labeledConversationSlice 
 */
@Serializable

internal data class DMInboxPinnedInboxQueryResponseData (

    @SerialName(value = "labeled_conversation_slice")
    val labeledConversationSlice: DMInboxPinnedInboxQueryResponseDataLabeledConversationSlice? = null

) {


}

