/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 * @param minEntryId 
 */
@Serializable

internal data class DMInboxTimelines (

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "min_entry_id")
    val minEntryId: kotlin.String? = null

) {


}

