/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMMessageSearchSlice

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dmMessageSliceResult 
 */
@Serializable

internal data class DMMessageSearchTabQueryResponseData (

    @SerialName(value = "dm_message_slice_result")
    val dmMessageSliceResult: DMMessageSearchSlice? = null

) {


}

