/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertyEntries 
 * @param users 
 */
@Serializable

internal data class DmNew2Response (

    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<InboxTimelineEntry>? = null,

    @SerialName(value = "users")
    val users: kotlin.collections.Map<kotlin.String, InboxUser>? = null

) {


}

