/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMPermissionsCreateGroupConversationResponsePermissionsIdKeysValue
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param idKeys
 */
@Serializable
internal data class DMPermissionsCreateGroupConversationResponsePermissions(
    @Contextual @SerialName(value = "id_keys")
    val idKeys: kotlin.collections.Map<kotlin.String, DMPermissionsCreateGroupConversationResponsePermissionsIdKeysValue>? = null,
)
