/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typename
 */
@Serializable
internal data class DMUseDMReactionMutationAddMutationResponseDataCreateDmReaction(
    @SerialName(value = "__typename")
    val typename: DMUseDMReactionMutationAddMutationResponseDataCreateDmReaction.Typename? = null,
) {
    /**
     *
     *
     * Values: CreateDMReactionSuccess
     */
    @Serializable
    public enum class Typename(
        public val value: kotlin.String,
    ) {
        @SerialName(value = "CreateDMReactionSuccess")
        CreateDMReactionSuccess("CreateDMReactionSuccess"),
    }
}
