/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 *
 *
 * @param hashtags
 * @param symbols
 * @param urls
 * @param userMentions
 * @param media
 */
@Serializable
internal data class Entities(
    @SerialName(value = "hashtags")
    val hashtags: JsonElement? = null,
    @SerialName(value = "symbols")
    val symbols: JsonElement? = null,
    @SerialName(value = "urls")
    val urls: kotlin.collections.List<Url>? = null,
    @SerialName(value = "user_mentions")
    val userMentions: JsonElement? = null,
    @SerialName(value = "media")
    val media: kotlin.collections.List<Media>? = null,
    @SerialName(value = "description")
    val description: Description? = null,
    @SerialName(value = "url")
    val url: Description? = null,
)

@Serializable
internal data class Description(
    @SerialName(value = "urls")
    val urls: kotlin.collections.List<Url>? = null,
)
