/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param hashtags
 * @param symbols
 * @param urls
 * @param userMentions
 * @param media
 */
@Serializable
data class Entities(
    @SerialName(value = "hashtags")
    val hashtags: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlin.Any>>,
    @SerialName(value = "symbols")
    val symbols: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlin.Any>>,
    @SerialName(value = "urls")
    val urls: kotlin.collections.List<Url>,
    @SerialName(value = "user_mentions")
    val userMentions: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlin.Any>>,
    @SerialName(value = "media")
    val media: kotlin.collections.List<Media>? = null,
)
