/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxUserEventReactionEntry
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param reactionCreate
 */
@Serializable
internal data class InboxTimelineReactionCreateEntry(
    @SerialName(value = "reaction_create")
    val reactionCreate: InboxUserEventReactionEntry? = null,
)
