/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param r 
 * @param ttl 
 */
@Serializable

internal data class InboxConversationTimelineMessageDataAttachmentMediaStats (

    @SerialName(value = "r")
    val r: kotlin.String? = null,

    @SerialName(value = "ttl")
    val ttl: kotlin.Int? = null

) {


}

