/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversation
import dev.dimension.flare.data.network.xqt.model.InboxUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cursor 
 * @param lastSeenEventId 
 * @param trustedLastSeenEventId 
 * @param untrustedLastSeenEventId 
 * @param users 
 * @param conversations 
 * @param propertyEntries 
 */
@Serializable

internal data class InboxDMUserUpdateResponseUserEvents (

    @SerialName(value = "cursor")
    val cursor: kotlin.String? = null,

    @SerialName(value = "last_seen_event_id")
    val lastSeenEventId: kotlin.String? = null,

    @SerialName(value = "trusted_last_seen_event_id")
    val trustedLastSeenEventId: kotlin.String? = null,

    @SerialName(value = "untrusted_last_seen_event_id")
    val untrustedLastSeenEventId: kotlin.String? = null,

    @Contextual @SerialName(value = "users")
    val users: kotlin.collections.Map<kotlin.String, InboxUser>? = null,

    @Contextual @SerialName(value = "conversations")
    val conversations: kotlin.collections.Map<kotlin.String, InboxConversation>? = null,

    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<@Contextual kotlin.Any>? = null

) {


}

