/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaSize
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param thumb
 * @param large
 * @param medium
 * @param small
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaSizes(
    @SerialName(value = "thumb")
    val thumb: InboxConversationTimelineMessageDataAttachmentMediaSize? = null,
    @SerialName(value = "large")
    val large: InboxConversationTimelineMessageDataAttachmentMediaSize? = null,
    @SerialName(value = "medium")
    val medium: InboxConversationTimelineMessageDataAttachmentMediaSize? = null,
    @SerialName(value = "small")
    val small: InboxConversationTimelineMessageDataAttachmentMediaSize? = null,
)
