/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxTimelineConversationAvatarUpdateEntryConversationAvatarUpdateAvatarImage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param image 
 */
@Serializable

internal data class InboxTimelineConversationAvatarUpdateEntryConversationAvatarUpdateAvatar (

    @SerialName(value = "image")
    val image: InboxTimelineConversationAvatarUpdateEntryConversationAvatarUpdateAvatarImage? = null

) {


}

