/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param url
 * @param expandedUrl
 * @param displayUrl
 * @param indices
 */
@Serializable
internal data class InboxConversationTimelineMessageDataEntitiesUrlEntity(
    @SerialName(value = "url")
    val url: kotlin.String? = null,
    @SerialName(value = "expanded_url")
    val expandedUrl: kotlin.String? = null,
    @SerialName(value = "display_url")
    val displayUrl: kotlin.String? = null,
    @SerialName(value = "indices")
    val indices: kotlin.collections.List<kotlin.Int>? = null,
)
