/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataEntitiesHashtagEntity
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataEntitiesSymbolEntity
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataEntitiesUrlEntity
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataEntitiesUserMentionEntity
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param hashtags
 * @param symbols
 * @param userMentions
 * @param urls
 */
@Serializable
internal data class InboxConversationTimelineMessageDataEntities(
    @SerialName(value = "hashtags")
    val hashtags: kotlin.collections.List<InboxConversationTimelineMessageDataEntitiesHashtagEntity>? = null,
    @SerialName(value = "symbols")
    val symbols: kotlin.collections.List<InboxConversationTimelineMessageDataEntitiesSymbolEntity>? = null,
    @SerialName(value = "user_mentions")
    val userMentions: kotlin.collections.List<InboxConversationTimelineMessageDataEntitiesUserMentionEntity>? = null,
    @SerialName(value = "urls")
    val urls: kotlin.collections.List<InboxConversationTimelineMessageDataEntitiesUrlEntity>? = null,
)
