/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachment
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataEntities
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param time
 * @param recipientId
 * @param senderId
 * @param text
 * @param editCount
 * @param entities
 * @param attachment
 */
@Serializable
internal data class InboxConversationTimelineMessageDataReplyData(
    @SerialName(value = "id")
    val id: kotlin.String? = null,
    @SerialName(value = "time")
    val time: kotlin.String? = null,
    @SerialName(value = "recipient_id")
    val recipientId: kotlin.String? = null,
    @SerialName(value = "sender_id")
    val senderId: kotlin.String? = null,
    @SerialName(value = "text")
    val text: kotlin.String? = null,
    @SerialName(value = "edit_count")
    val editCount: kotlin.Int? = null,
    @SerialName(value = "entities")
    val entities: InboxConversationTimelineMessageDataEntities? = null,
    @SerialName(value = "attachment")
    val attachment: InboxConversationTimelineMessageDataAttachment? = null,
)
