/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentAnimatedGif
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentPhoto
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentVideo
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param photo
 * @param animatedGif
 * @param video
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachment(
    @SerialName(value = "photo")
    val photo: InboxConversationTimelineMessageDataAttachmentPhoto? = null,
    @SerialName(value = "animated_gif")
    val animatedGif: InboxConversationTimelineMessageDataAttachmentAnimatedGif? = null,
    @SerialName(value = "video")
    val video: InboxConversationTimelineMessageDataAttachmentVideo? = null,
)
