/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaOriginalInfo
import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaSizes
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param idStr
 * @param indices
 * @param mediaUrl
 * @param mediaUrlHttps
 * @param url
 * @param displayUrl
 * @param expandedUrl
 * @param type
 * @param originalInfo
 * @param sizes
 * @param features
 * @param extAltText
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentPhoto(
    @SerialName(value = "id")
    val id: kotlin.Long? = null,
    @SerialName(value = "id_str")
    val idStr: kotlin.String? = null,
    @SerialName(value = "indices")
    val indices: kotlin.collections.List<kotlin.Int>? = null,
    @SerialName(value = "media_url")
    val mediaUrl: kotlin.String? = null,
    @SerialName(value = "media_url_https")
    val mediaUrlHttps: kotlin.String? = null,
    @SerialName(value = "url")
    val url: kotlin.String? = null,
    @SerialName(value = "display_url")
    val displayUrl: kotlin.String? = null,
    @SerialName(value = "expanded_url")
    val expandedUrl: kotlin.String? = null,
    @SerialName(value = "type")
    val type: kotlin.String? = null,
    @SerialName(value = "original_info")
    val originalInfo: InboxConversationTimelineMessageDataAttachmentMediaOriginalInfo? = null,
    @SerialName(value = "sizes")
    val sizes: InboxConversationTimelineMessageDataAttachmentMediaSizes? = null,
//    @Contextual @SerialName(value = "features")
//    val features: kotlin.Any? = null,
    @SerialName(value = "ext_alt_text")
    val extAltText: kotlin.String? = null,
)
