/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxTimelineConversationCreateEntryConversationCreate

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param conversationCreate 
 */
@Serializable

internal data class InboxTimelineConversationCreateEntry (

    @SerialName(value = "conversation_create")
    val conversationCreate: InboxTimelineConversationCreateEntryConversationCreate? = null

) {


}

