/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaExtMediaColor
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param ok
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaColorR(
    @SerialName(value = "ok")
    val ok: InboxConversationTimelineMessageDataAttachmentMediaExtMediaColor? = null,
)
