/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxUserEntitiesUrl

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param description 
 */
@Serializable

internal data class InboxUserEntities (

    @SerialName(value = "url")
    val url: InboxUserEntitiesUrl? = null,

    @SerialName(value = "description")
    val description: InboxUserEntitiesUrl? = null

) {


}

