/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaVideoVariant

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param aspectRatio 
 * @param durationMillis 
 * @param variants 
 */
@Serializable

internal data class InboxConversationTimelineMessageDataAttachmentMediaVideoInfo (

    @SerialName(value = "aspect_ratio")
    val aspectRatio: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "duration_millis")
    val durationMillis: kotlin.Int? = null,

    @SerialName(value = "variants")
    val variants: kotlin.collections.List<InboxConversationTimelineMessageDataAttachmentMediaVideoVariant>? = null

) {


}

