/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxTimelineMessageDeleteORMarkAsSpamEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param messageMarkAsSpam 
 */
@Serializable

internal data class InboxTimelineMessageMarkAsSpamEntry (

    @SerialName(value = "message_mark_as_spam")
    val messageMarkAsSpam: InboxTimelineMessageDeleteORMarkAsSpamEntry? = null

) {


}

