/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineConversation
import dev.dimension.flare.data.network.xqt.model.InboxUser
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param status
 * @param minEntryId
 * @param maxEntryId
 * @param propertyEntries
 * @param users
 * @param conversations
 */
@Serializable
internal data class InboxConversationTimelineData(
    @SerialName(value = "status")
    val status: kotlin.String? = null,
    @SerialName(value = "min_entry_id")
    val minEntryId: kotlin.String? = null,
    @SerialName(value = "max_entry_id")
    val maxEntryId: kotlin.String? = null,
    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<InboxTimelineEntry>? = null,
    @Contextual @SerialName(value = "users")
    val users: kotlin.collections.Map<kotlin.String, InboxUser>? = null,
    @Contextual @SerialName(value = "conversations")
    val conversations: kotlin.collections.Map<kotlin.String, InboxConversation>? = null,
)
