/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.InboxConversationTimelineMessageDataAttachmentMediaRGB

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rgb 
 * @param percentage 
 */
@Serializable

internal data class InboxConversationTimelineMessageDataAttachmentMediaColorPalette (

    @SerialName(value = "rgb")
    val rgb: InboxConversationTimelineMessageDataAttachmentMediaRGB? = null,

    @SerialName(value = "percentage")
    val percentage: kotlin.Float? = null

) {


}

