/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 *
 *
 * @param propertyEntries
 * @param type
 * @param moduleEntryId
 * @param moduleItems
 * @param entry
 * @param entryIdToReplace
 * @param richText
 * @param usersResults
 * @param direction
 * @param clientEventInfo
 * @param cover
 * @param prepend
 * @param alertType
 * @param colorConfig
 * @param displayDurationMs
 * @param displayLocation
 * @param iconDisplayInfo
 * @param triggerDelayMs
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("type")
internal sealed interface InstructionUnion
