/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param large
 * @param medium
 * @param small
 * @param thumb
 */
@Serializable
data class MediaSizes(
    @SerialName(value = "large")
    val large: MediaSize,
    @SerialName(value = "medium")
    val medium: MediaSize,
    @SerialName(value = "small")
    val small: MediaSize,
    @SerialName(value = "thumb")
    val thumb: MediaSize,
)
