/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param entryId
 * @param item
 */
@Serializable
data class ModuleItem(
    @SerialName(value = "entryId")
    val entryId: kotlin.String,
    @SerialName(value = "item")
    val item: ModuleEntry,
)
