/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param index
 * @param mediaId
 */
@Serializable
internal data class NoteTweetResultMediaInlineMedia(
    @SerialName(value = "index")
    val index: kotlin.Int,
    @SerialName(value = "media_id")
    val mediaId: kotlin.String,
)
