/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param mediaEntities
 * @param possiblySensitive
 */
@Serializable
internal data class PostCreateTweetRequestVariablesMedia(
    @SerialName(value = "media_entities")
    val mediaEntities: kotlin.collections.List<PostCreateTweetRequestVariablesMediaMediaEntitiesInner>,
    @SerialName(value = "possibly_sensitive")
    val possiblySensitive: kotlin.Boolean = false,
)
