/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param contextType
 * @param text
 * @param type
 */
@Serializable
data class SocialContext(
    @SerialName(value = "contextType")
    val contextType: kotlin.String? = null,
    @SerialName(value = "text")
    val text: kotlin.String? = null,
    @SerialName(value = "type")
    val type: kotlin.String? = null,
)
