/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typename
 * @param cursorType
 * @param `value`
 * @param entryType
 * @param itemType
 */
@Serializable
@SerialName("TimelineTimelineCursor")
data class TimelineTimelineCursor(
//    @Contextual @SerialName(value = "__typename")
//    val typename: TypeName,
    @Contextual @SerialName(value = "cursorType")
    val cursorType: CursorType,
    @SerialName(value = "value")
    val `value`: kotlin.String,
    @Contextual @SerialName(value = "entryType")
    val entryType: ContentEntryType? = null,
    @Contextual @SerialName(value = "itemType")
    val itemType: ContentEntryType? = null,
) : ContentUnion, ItemContentUnion
