/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typename
 * @param itemType
 * @param tweetDisplayType
 * @param tweetResults
 * @param socialContext
 * @param promotedMetadata
 */
@Serializable
data class TimelineTweet(
    @Contextual @SerialName(value = "__typename")
    val typename: TypeName,
    @Contextual @SerialName(value = "itemType")
    val itemType: ContentItemType,
    @SerialName(value = "tweetDisplayType")
    val tweetDisplayType: kotlin.String,
    @SerialName(value = "tweet_results")
    val tweetResults: ItemResult,
    @SerialName(value = "SocialContext")
    val socialContext: SocialContext? = null,
    @Contextual @SerialName(value = "promotedMetadata")
    val promotedMetadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
)
