/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param propertyEntries
 * @param type
 */
@Serializable
data class TimelineAddEntries(
    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<TimelineAddEntry>,
    @Contextual @SerialName(value = "type")
    val type: InstructionType,
)
