/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param moduleEntryId
 * @param moduleItems
 * @param type
 * @param prepend
 */
@Serializable
data class TimelineAddToModule(
    @SerialName(value = "moduleEntryId")
    val moduleEntryId: kotlin.String,
    @SerialName(value = "moduleItems")
    val moduleItems: kotlin.collections.List<ModuleItem>,
    @Contextual @SerialName(value = "type")
    val type: InstructionType,
    @SerialName(value = "prepend")
    val prepend: kotlin.Boolean? = null,
)
