/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param editControlInitial
 * @param editTweetIds
 * @param editableUntilMsecs
 * @param editsRemaining
 * @param initialTweetId
 * @param isEditEligible
 */
@Serializable
internal data class TweetEditControl(
    @SerialName(value = "edit_control_initial")
    val editControlInitial: TweetEditControlInitial? = null,
    @SerialName(value = "edit_tweet_ids")
    val editTweetIds: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "editable_until_msecs")
    val editableUntilMsecs: kotlin.String? = null,
    @SerialName(value = "edits_remaining")
    val editsRemaining: kotlin.String? = null,
    @SerialName(value = "initial_tweet_id")
    val initialTweetId: kotlin.String? = null,
    @SerialName(value = "is_edit_eligible")
    val isEditEligible: kotlin.Boolean? = null,
)
