/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param editTweetIds
 * @param editableUntilMsecs
 * @param editsRemaining
 * @param isEditEligible
 */
@Serializable
data class TweetEditControlInitial(
    @SerialName(value = "edit_tweet_ids")
    val editTweetIds: kotlin.collections.List<kotlin.String>,
    @SerialName(value = "editable_until_msecs")
    val editableUntilMsecs: kotlin.String,
    @SerialName(value = "edits_remaining")
    val editsRemaining: kotlin.String,
    @SerialName(value = "is_edit_eligible")
    val isEditEligible: kotlin.Boolean,
)
