/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param bookmarkCount
 * @param bookmarked
 * @param conversationIdStr
 * @param createdAt
 * @param displayTextRange
 * @param entities
 * @param favoriteCount
 * @param favorited
 * @param fullText
 * @param idStr
 * @param isQuoteStatus
 * @param lang
 * @param quoteCount
 * @param replyCount
 * @param retweetCount
 * @param retweeted
 * @param userIdStr
 * @param extendedEntities
 * @param possiblySensitive
 * @param possiblySensitiveEditable
 * @param retweetedStatusResult
 * @param selfThread
 */
@Serializable
internal data class TweetLegacy(
    @SerialName(value = "bookmark_count")
    val bookmarkCount: kotlin.Int? = null,
    @SerialName(value = "bookmarked")
    val bookmarked: kotlin.Boolean? = null,
    @SerialName(value = "conversation_id_str")
    val conversationIdStr: kotlin.String,
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,
    @SerialName(value = "display_text_range")
    val displayTextRange: kotlin.collections.List<kotlin.Int>,
    @SerialName(value = "entities")
    val entities: Entities,
    @SerialName(value = "favorite_count")
    val favoriteCount: kotlin.Int,
    @SerialName(value = "favorited")
    val favorited: kotlin.Boolean,
    @SerialName(value = "full_text")
    val fullText: kotlin.String,
    @SerialName(value = "id_str")
    val idStr: kotlin.String,
    @SerialName(value = "is_quote_status")
    val isQuoteStatus: kotlin.Boolean,
    @SerialName(value = "lang")
    val lang: kotlin.String,
    @SerialName(value = "quote_count")
    val quoteCount: kotlin.Int,
    @SerialName(value = "reply_count")
    val replyCount: kotlin.Int,
    @SerialName(value = "retweet_count")
    val retweetCount: kotlin.Int,
    @SerialName(value = "retweeted")
    val retweeted: kotlin.Boolean,
    @SerialName(value = "user_id_str")
    val userIdStr: kotlin.String,
    @SerialName(value = "extended_entities")
    val extendedEntities: ExtendedEntities? = null,
    @SerialName(value = "possibly_sensitive")
    val possiblySensitive: kotlin.Boolean? = false,
    @SerialName(value = "possibly_sensitive_editable")
    val possiblySensitiveEditable: kotlin.Boolean? = false,
    @SerialName(value = "retweeted_status_result")
    val retweetedStatusResult: ItemResult? = null,
    @SerialName(value = "self_thread")
    val selfThread: SelfThread? = null,
    val in_reply_to_screen_name: String? = null,
    val in_reply_to_status_id_str: String? = null,
    val in_reply_to_user_id_str: String? = null,
    /**
     * only for dm message
     */
    @SerialName("user")
    val user: InboxUser? = null,
)
