/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param enabled
 * @param endTime
 * @param startTime
 */
@Serializable
internal data class UpdateAccountSettingsResponseSleepTime(
    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,
    @SerialName(value = "end_time")
    val endTime: kotlin.String? = null,
    @SerialName(value = "start_time")
    val startTime: kotlin.String? = null,
)
