/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * Values: timelineTweet,timelineTimelineCursor,timelineUser,timelinePrompt,timelineMessagePrompt,timelineCommunity
 */
@Serializable
internal enum class ContentItemType(
    val value: kotlin.String,
) {
    @SerialName(value = "TimelineTweet")
    timelineTweet("TimelineTweet"),

    @SerialName(value = "TimelineTimelineCursor")
    timelineTimelineCursor("TimelineTimelineCursor"),

    @SerialName(value = "TimelineUser")
    timelineUser("TimelineUser"),

    @SerialName(value = "TimelinePrompt")
    timelinePrompt("TimelinePrompt"),

    @SerialName(value = "TimelineMessagePrompt")
    timelineMessagePrompt("TimelineMessagePrompt"),

    @SerialName(value = "TimelineCommunity")
    timelineCommunity("TimelineCommunity"),

    @SerialName(value = "TimelineTwitterList")
    timelineTwitterList("TimelineTwitterList"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ContentItemType) "$data" else null

        /**
         * Returns a valid [ContentItemType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ContentItemType? =
            data?.let {
                val normalizedData = "$it".lowercase()
                values().firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
