/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import dev.dimension.flare.data.network.xqt.model.DMInboxPinnedConversationParticipantUserResults
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param userResults
 */
@Serializable
internal data class DMInboxPinnedConversationParticipant(
    @SerialName(value = "user_results")
    val userResults: DMInboxPinnedConversationParticipantUserResults? = null,
)
