/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param bitrate
 * @param contentType
 * @param url
 */
@Serializable
internal data class InboxConversationTimelineMessageDataAttachmentMediaVideoVariant(
    @SerialName(value = "bitrate")
    val bitrate: kotlin.Int? = null,
    @SerialName(value = "content_type")
    val contentType: kotlin.String? = null,
    @SerialName(value = "url")
    val url: kotlin.String? = null,
)
