/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param communitiesActions
 * @param country
 * @param guestId
 * @param hasCommunityMemberships
 * @param isActiveCreator
 * @param isRestrictedSession
 * @param isSuperFollowSubscriber
 * @param language
 * @param oneFactorLoginEligibility
 * @param superFollowersCount
 * @param superFollowsApplicationStatus
 * @param userFeatures
 * @param userId
 * @param ssoInitTokens
 */
@Serializable
internal data class Session(
    @SerialName(value = "communitiesActions")
    val communitiesActions: CommunitiesActions,
    @SerialName(value = "country")
    val country: kotlin.String,
    @SerialName(value = "guestId")
    val guestId: kotlin.String,
    @SerialName(value = "hasCommunityMemberships")
    val hasCommunityMemberships: kotlin.Boolean,
    @SerialName(value = "isActiveCreator")
    val isActiveCreator: kotlin.Boolean,
    @SerialName(value = "isRestrictedSession")
    val isRestrictedSession: kotlin.Boolean,
    @SerialName(value = "isSuperFollowSubscriber")
    val isSuperFollowSubscriber: kotlin.Boolean,
    @SerialName(value = "language")
    val language: kotlin.String,
    @SerialName(value = "oneFactorLoginEligibility")
    val oneFactorLoginEligibility: OneFactorLoginEligibility,
    @SerialName(value = "superFollowersCount")
    val superFollowersCount: kotlin.Int,
    @SerialName(value = "superFollowsApplicationStatus")
    val superFollowsApplicationStatus: Session.SuperFollowsApplicationStatus,
    @SerialName(value = "userFeatures")
    val userFeatures: UserFeatures,
    @SerialName(value = "user_id")
    val userId: kotlin.String,
    @Contextual @SerialName(value = "SsoInitTokens")
    val ssoInitTokens: kotlin.Any? = null,
) {
    /**
     *
     *
     * Values: notStarted
     */
    @Serializable
    enum class SuperFollowsApplicationStatus(
        val value: kotlin.String,
    ) {
        @SerialName(value = "NotStarted")
        notStarted("NotStarted"),
    }
}
