/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.xqt.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 *
 *
 * @param entities
 * @param text
 */
@Serializable
internal data class TimelineShowAlertRichText(
    @SerialName(value = "entities")
    val entities: JsonElement? = null,
    @SerialName(value = "text")
    val text: kotlin.String? = null,
)
