/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param deliver * @param inbox * @param db * @param objectStorage */
@Serializable

data class AdminQueueStats200Response(

    @SerialName(value = "deliver") @Required val deliver: QueueCount,

    @SerialName(value = "inbox") @Required val inbox: QueueCount,

    @SerialName(value = "db") @Required val db: QueueCount,

    @SerialName(value = "objectStorage") @Required val objectStorage: QueueCount

)
