/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param ids * @param aliases */
@Serializable

data class AdminEmojiAddAliasesBulkRequest(

    @SerialName(value = "ids") @Required val ids: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "aliases") @Required val aliases: kotlin.collections.List<kotlin.String>

)
