/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param roleId * @param name * @param description * @param color * @param iconUrl * @param target * @param condFormula * @param isPublic * @param isModerator * @param isAdministrator * @param asBadge * @param canEditMembersByModerator * @param displayOrder * @param policies * @param isExplorable */
@Serializable

data class AdminRolesUpdateRequest(

    @SerialName(value = "roleId") @Required val roleId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "color") @Required val color: kotlin.String?,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String?,

    @SerialName(value = "target") @Required val target: AdminRolesUpdateRequest.Target,

    @SerialName(value = "condFormula") @Required val condFormula: kotlin.String,

    @SerialName(value = "isPublic") @Required val isPublic: kotlin.Boolean,

    @SerialName(value = "isModerator") @Required val isModerator: kotlin.Boolean,

    @SerialName(value = "isAdministrator") @Required val isAdministrator: kotlin.Boolean,

    @SerialName(value = "asBadge") @Required val asBadge: kotlin.Boolean,

    @SerialName(value = "canEditMembersByModerator") @Required val canEditMembersByModerator: kotlin.Boolean,

    @SerialName(value = "displayOrder") @Required val displayOrder: kotlin.Double,

    @SerialName(value = "policies") @Required val policies: kotlin.String,

    @SerialName(value = "isExplorable") val isExplorable: kotlin.Boolean? = null

) {

    /**
     * *
     * Values: Manual,Conditional
     */
    @Serializable
    enum class Target(val value: kotlin.String) {
        @SerialName(value = "manual")
        Manual("manual"),

        @SerialName(value = "conditional")
        Conditional("conditional");
    }
}
