/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param url * @param memo * @param place * @param priority * @param ratio * @param expiresAt * @param startsAt * @param imageUrl * @param dayOfWeek */
@Serializable

data class AdminAdCreateRequest(

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "memo") @Required val memo: kotlin.String,

    @SerialName(value = "place") @Required val place: kotlin.String,

    @SerialName(value = "priority") @Required val priority: kotlin.String,

    @SerialName(value = "ratio") @Required val ratio: kotlin.Int,

    @SerialName(value = "expiresAt") @Required val expiresAt: kotlin.Int,

    @SerialName(value = "startsAt") @Required val startsAt: kotlin.Int,

    @SerialName(value = "imageUrl") @Required val imageUrl: kotlin.String,

    @SerialName(value = "dayOfWeek") @Required val dayOfWeek: kotlin.Int

)
