/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * *
 * @param name * @param targetUserPattern * @param reporterPattern * @param reportContentPattern * @param expiresAt * @param forward */
@Serializable

data class AdminAbuseReportResolverCreate200Response(

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "targetUserPattern") @Required val targetUserPattern: kotlin.String?,

    @SerialName(value = "reporterPattern") @Required val reporterPattern: kotlin.String?,

    @SerialName(value = "reportContentPattern") @Required val reportContentPattern: kotlin.String?,

    @SerialName(value = "expiresAt") @Required val expiresAt: kotlin.String,

    @SerialName(value = "forward") @Required val forward: kotlin.Boolean

)
