/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param comment * @param resolved * @param reporterId * @param targetUserId * @param assigneeId * @param reporter * @param targetUser * @param assignee */
@Serializable

data class AdminAbuseUserReports200ResponseInner(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "comment") @Required val comment: kotlin.String,

    @SerialName(value = "resolved") @Required val resolved: kotlin.Boolean,

    @SerialName(value = "reporterId") @Required val reporterId: kotlin.String,

    @SerialName(value = "targetUserId") @Required val targetUserId: kotlin.String,

    @SerialName(value = "assigneeId") @Required val assigneeId: kotlin.String?,

    @SerialName(value = "reporter") @Required val reporter: User,

    @SerialName(value = "targetUser") @Required val targetUser: User,

    @SerialName(value = "assignee") val assignee: User? = null

)
