/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param type */
@Serializable

data class AdminQueuePromoteRequest(

    @SerialName(value = "type") @Required val type: AdminQueuePromoteRequest.Type

) {

    /**
     * *
     * Values: Deliver,Inbox
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "deliver")
        Deliver("deliver"),

        @SerialName(value = "inbox")
        Inbox("inbox");
    }
}
