/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param updatedAt * @param text * @param title * @param imageUrl * @param isPrivate * @param closeDuration * @param isRead */
@Serializable

data class Announcements200ResponseInner(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String?,

    @SerialName(value = "text") @Required val text: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "imageUrl") @Required val imageUrl: kotlin.String?,

    @SerialName(value = "isPrivate") @Required val isPrivate: kotlin.Boolean?,

    @SerialName(value = "closeDuration") @Required val closeDuration: kotlin.Double,

    @SerialName(value = "isRead") val isRead: kotlin.Boolean? = null

)
