/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param name * @param keywords * @param excludeKeywords * @param src * @param userListId * @param users * @param caseSensitive * @param notify * @param withReplies * @param withFile * @param isActive * @param hasUnreadNote */
@Serializable

data class Antenna(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "keywords") @Required val keywords: kotlin.collections.List<kotlin.collections.List<kotlin.String>>,

    @SerialName(value = "excludeKeywords") @Required val excludeKeywords: kotlin.collections.List<kotlin.collections.List<kotlin.String>>,

    @SerialName(value = "src") @Required val src: Antenna.Src,

    @SerialName(value = "userListId") @Required val userListId: kotlin.String?,

    @SerialName(value = "users") @Required val users: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "caseSensitive") @Required val caseSensitive: kotlin.Boolean = false,

    @SerialName(value = "notify") @Required val notify: kotlin.Boolean,

    @SerialName(value = "withReplies") @Required val withReplies: kotlin.Boolean = false,

    @SerialName(value = "withFile") @Required val withFile: kotlin.Boolean,

    @SerialName(value = "isActive") @Required val isActive: kotlin.Boolean,

    @SerialName(value = "hasUnreadNote") @Required val hasUnreadNote: kotlin.Boolean = false

) {

    /**
     * *
     * Values: Home,All,Users,List
     */
    @Serializable
    enum class Src(val value: kotlin.String) {
        @SerialName(value = "home")
        Home("home"),

        @SerialName(value = "all")
        All("all"),

        @SerialName(value = "users")
        Users("users"),

        @SerialName(value = "list")
        List("list");
    }
}
