/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param totalCount * @param totalSize * @param incCount * @param incSize * @param decCount * @param decSize */
@Serializable
data class ChartsUserDrive200Response(

    @SerialName(value = "totalCount") val totalCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "totalSize") val totalSize: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "incCount") val incCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "incSize") val incSize: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "decCount") val decCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "decSize") val decSize: kotlin.collections.List<kotlin.Double>,

)
