/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param localIncCount * @param localIncSize * @param localDecCount * @param localDecSize * @param remoteIncCount * @param remoteIncSize * @param remoteDecCount * @param remoteDecSize */
@Serializable

data class ChartsDrive200Response(

    @SerialName(value = "local.incCount") @Required val localIncCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "local.incSize") @Required val localIncSize: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "local.decCount") @Required val localDecCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "local.decSize") @Required val localDecSize: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.incCount") @Required val remoteIncCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.incSize") @Required val remoteIncSize: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.decCount") @Required val remoteDecCount: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "remote.decSize") @Required val remoteDecSize: kotlin.collections.List<kotlin.Double>

)
