/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param readWrite * @param read * @param write * @param registeredWithinWeek * @param registeredWithinMonth * @param registeredWithinYear * @param registeredOutsideWeek * @param registeredOutsideMonth * @param registeredOutsideYear */
@Serializable

data class ChartsActiveUsers200Response(

    @SerialName(value = "readWrite") @Required val readWrite: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "read") @Required val read: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "write") @Required val write: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredWithinWeek") @Required val registeredWithinWeek: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredWithinMonth") @Required val registeredWithinMonth: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredWithinYear") @Required val registeredWithinYear: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredOutsideWeek") @Required val registeredOutsideWeek: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredOutsideMonth") @Required val registeredOutsideMonth: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "registeredOutsideYear") @Required val registeredOutsideYear: kotlin.collections.List<kotlin.Double>

)
