/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param lastClippedAt * @param userId * @param user * @param name * @param description * @param isPublic * @param favoritedCount * @param isFavorited */
@Serializable

data class Clip(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "lastClippedAt") @Required val lastClippedAt: kotlin.String?,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "user") @Required val user: UserLite,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String?,

    @SerialName(value = "isPublic") @Required val isPublic: kotlin.Boolean,

    @SerialName(value = "favoritedCount") @Required val favoritedCount: kotlin.Double,

    @SerialName(value = "isFavorited") val isFavorited: kotlin.Boolean? = null

)
