/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param firstRetrievedAt * @param host * @param usersCount * @param notesCount * @param followingCount * @param followersCount * @param isNotResponding * @param isSuspended * @param isBlocked * @param softwareName * @param softwareVersion * @param openRegistrations * @param name * @param description * @param maintainerName * @param maintainerEmail * @param iconUrl * @param faviconUrl * @param themeColor * @param infoUpdatedAt */
@Serializable

data class FederationShowInstance200Response(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "firstRetrievedAt") @Required val firstRetrievedAt: kotlin.String,

    @SerialName(value = "host") @Required val host: kotlin.String,

    @SerialName(value = "usersCount") @Required val usersCount: kotlin.Double,

    @SerialName(value = "notesCount") @Required val notesCount: kotlin.Double,

    @SerialName(value = "followingCount") @Required val followingCount: kotlin.Double,

    @SerialName(value = "followersCount") @Required val followersCount: kotlin.Double,

    @SerialName(value = "isNotResponding") @Required val isNotResponding: kotlin.Boolean,

    @SerialName(value = "isSuspended") @Required val isSuspended: kotlin.Boolean,

    @SerialName(value = "isBlocked") @Required val isBlocked: kotlin.Boolean,

    @SerialName(value = "softwareName") @Required val softwareName: kotlin.String?,

    @SerialName(value = "softwareVersion") @Required val softwareVersion: kotlin.String?,

    @SerialName(value = "openRegistrations") @Required val openRegistrations: kotlin.Boolean?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "description") @Required val description: kotlin.String?,

    @SerialName(value = "maintainerName") @Required val maintainerName: kotlin.String?,

    @SerialName(value = "maintainerEmail") @Required val maintainerEmail: kotlin.String?,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String?,

    @SerialName(value = "faviconUrl") @Required val faviconUrl: kotlin.String?,

    @SerialName(value = "themeColor") @Required val themeColor: kotlin.String?,

    @SerialName(value = "infoUpdatedAt") @Required val infoUpdatedAt: kotlin.String?

)
