/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param flashId * @param title * @param summary * @param script * @param permissions */
@Serializable

data class FlashUpdateRequest(

    @SerialName(value = "flashId") @Required val flashId: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "summary") @Required val summary: kotlin.String,

    @SerialName(value = "script") @Required val script: kotlin.String,

    @SerialName(value = "permissions") @Required val permissions: kotlin.collections.List<kotlin.String>

)
