/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param follower * @param followee */
@Serializable

data class FollowingRequestsList200ResponseInner(

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "follower") val follower: UserLite,

    @SerialName(value = "followee") val followee: UserLite

)
