/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param tag * @param mentionedUsersCount * @param mentionedLocalUsersCount * @param mentionedRemoteUsersCount * @param attachedUsersCount * @param attachedLocalUsersCount * @param attachedRemoteUsersCount */
@Serializable

data class Hashtag(

    @SerialName(value = "tag") @Required val tag: kotlin.String,

    @SerialName(value = "mentionedUsersCount") @Required val mentionedUsersCount: kotlin.Double,

    @SerialName(value = "mentionedLocalUsersCount") @Required val mentionedLocalUsersCount: kotlin.Double,

    @SerialName(value = "mentionedRemoteUsersCount") @Required val mentionedRemoteUsersCount: kotlin.Double,

    @SerialName(value = "attachedUsersCount") @Required val attachedUsersCount: kotlin.Double,

    @SerialName(value = "attachedLocalUsersCount") @Required val attachedLocalUsersCount: kotlin.Double,

    @SerialName(value = "attachedRemoteUsersCount") @Required val attachedRemoteUsersCount: kotlin.Double

)
