/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param maintainerName * @param maintainerEmail * @param version * @param name * @param uri * @param description * @param langs * @param tosUrl * @param repositoryUrl * @param feedbackUrl * @param defaultDarkTheme * @param defaultLightTheme * @param disableRegistration * @param cacheRemoteFiles * @param cacheRemoteSensitiveFiles * @param emailRequiredForSignup * @param enableHcaptcha * @param hcaptchaSiteKey * @param enableRecaptcha * @param recaptchaSiteKey * @param enableTurnstile * @param turnstileSiteKey * @param swPublickey * @param mascotImageUrl * @param bannerUrl * @param serverErrorImageUrl * @param infoImageUrl * @param notFoundImageUrl * @param iconUrl * @param maxNoteTextLength * @param ads * @param requireSetup * @param enableEmail * @param enableServiceWorker * @param translatorAvailable * @param proxyAccountName * @param mediaProxy * @param features */
@Serializable

data class Meta200Response(

    @SerialName(value = "maintainerName") @Required val maintainerName: kotlin.String?,

    @SerialName(value = "maintainerEmail") @Required val maintainerEmail: kotlin.String?,

    @SerialName(value = "version") @Required val version: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "uri") @Required val uri: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String?,

    @SerialName(value = "langs") @Required val langs: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tosUrl") @Required val tosUrl: kotlin.String?,

    @SerialName(value = "repositoryUrl") @Required val repositoryUrl: kotlin.String = "https://github.com/misskey-dev/misskey",

    @SerialName(value = "feedbackUrl") @Required val feedbackUrl: kotlin.String = "https://github.com/misskey-dev/misskey/issues/new",

    @SerialName(value = "defaultDarkTheme") @Required val defaultDarkTheme: kotlin.String?,

    @SerialName(value = "defaultLightTheme") @Required val defaultLightTheme: kotlin.String?,

    @SerialName(value = "disableRegistration") @Required val disableRegistration: kotlin.Boolean,

    @SerialName(value = "cacheRemoteFiles") @Required val cacheRemoteFiles: kotlin.Boolean,

    @SerialName(value = "cacheRemoteSensitiveFiles") @Required val cacheRemoteSensitiveFiles: kotlin.Boolean,

    @SerialName(value = "emailRequiredForSignup") @Required val emailRequiredForSignup: kotlin.Boolean,

    @SerialName(value = "enableHcaptcha") @Required val enableHcaptcha: kotlin.Boolean,

    @SerialName(value = "hcaptchaSiteKey") @Required val hcaptchaSiteKey: kotlin.String?,

    @SerialName(value = "enableRecaptcha") @Required val enableRecaptcha: kotlin.Boolean,

    @SerialName(value = "recaptchaSiteKey") @Required val recaptchaSiteKey: kotlin.String?,

    @SerialName(value = "enableTurnstile") @Required val enableTurnstile: kotlin.Boolean,

    @SerialName(value = "turnstileSiteKey") @Required val turnstileSiteKey: kotlin.String?,

    @SerialName(value = "swPublickey") @Required val swPublickey: kotlin.String?,

    @SerialName(value = "mascotImageUrl") @Required val mascotImageUrl: kotlin.String = "/assets/ai.png",

    @SerialName(value = "bannerUrl") @Required val bannerUrl: kotlin.String,

    @SerialName(value = "serverErrorImageUrl") @Required val serverErrorImageUrl: kotlin.String?,

    @SerialName(value = "infoImageUrl") @Required val infoImageUrl: kotlin.String?,

    @SerialName(value = "notFoundImageUrl") @Required val notFoundImageUrl: kotlin.String?,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String?,

    @SerialName(value = "maxNoteTextLength") @Required val maxNoteTextLength: kotlin.Double,

    @SerialName(value = "ads") @Required val ads: kotlin.collections.List<Meta200ResponseAdsInner>,

    @SerialName(value = "requireSetup") @Required val requireSetup: kotlin.Boolean,

    @SerialName(value = "enableEmail") @Required val enableEmail: kotlin.Boolean,

    @SerialName(value = "enableServiceWorker") @Required val enableServiceWorker: kotlin.Boolean,

    @SerialName(value = "translatorAvailable") @Required val translatorAvailable: kotlin.Boolean,

    @SerialName(value = "proxyAccountName") @Required val proxyAccountName: kotlin.String?,

    @SerialName(value = "mediaProxy") @Required val mediaProxy: kotlin.String,

    @SerialName(value = "features") val features: Meta200ResponseFeatures? = null

)
