/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param noteId * @param targetLang */
@Serializable

data class NotesTranslateRequest(

    @SerialName(value = "noteId") @Required val noteId: kotlin.String,

    @SerialName(value = "targetLang") @Required val targetLang: kotlin.String

)
