/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param createdAt * @param updatedAt * @param title * @param name * @param summary * @param content * @param variables * @param userId * @param user */
@Serializable

data class Page(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "summary") @Required val summary: kotlin.String?,

    @SerialName(value = "content") @Required val content: kotlin.collections.List<String>,

    @SerialName(value = "variables") @Required val variables: kotlin.collections.List<String>,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "user") @Required val user: UserLite

)
