/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param name * @param username * @param host The local host is represented with `null`.
 * @param avatarUrl * @param avatarBlurhash * @param onlineStatus * @param url * @param uri * @param movedToUri * @param alsoKnownAs * @param createdAt * @param updatedAt * @param lastFetchedAt * @param bannerUrl * @param bannerBlurhash * @param isLocked * @param isSilenced * @param isLimited * @param isSuspended * @param description * @param location * @param birthday * @param lang * @param fields * @param followersCount * @param followingCount * @param notesCount * @param pinnedNoteIds * @param pinnedNotes * @param pinnedPageId * @param pinnedPage * @param publicReactions * @param twoFactorEnabled * @param usePasswordLessLogin * @param securityKeys * @param isAdmin * @param isModerator * @param isBot * @param isCat * @param isFollowing * @param isFollowed * @param hasPendingFollowRequestFromYou * @param hasPendingFollowRequestToYou * @param isBlocking * @param isBlocked * @param isMuted * @param isRenoteMuted * @param memo */
@Serializable

data class UserDetailedNotMe(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* The local host is represented with `null`. */
    @SerialName(value = "host") @Required val host: kotlin.String?,

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String?,

    @SerialName(value = "avatarBlurhash") @Required val avatarBlurhash: kotlin.String?,

    @SerialName(value = "onlineStatus") @Required val onlineStatus: UserDetailedNotMe.OnlineStatus?,

    @SerialName(value = "url") @Required val url: kotlin.String?,

    @SerialName(value = "uri") @Required val uri: kotlin.String?,

    @SerialName(value = "movedToUri") @Required val movedToUri: kotlin.String?,

    @SerialName(value = "alsoKnownAs") @Required val alsoKnownAs: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String?,

    @SerialName(value = "lastFetchedAt") @Required val lastFetchedAt: kotlin.String?,

    @SerialName(value = "bannerUrl") @Required val bannerUrl: kotlin.String?,

    @SerialName(value = "bannerBlurhash") @Required val bannerBlurhash: kotlin.String?,

    @SerialName(value = "isLocked") @Required val isLocked: kotlin.Boolean,

    @SerialName(value = "isSilenced") @Required val isSilenced: kotlin.Boolean,

    @SerialName(value = "isLimited") @Required val isLimited: kotlin.Boolean,

    @SerialName(value = "isSuspended") @Required val isSuspended: kotlin.Boolean,

    @SerialName(value = "description") @Required val description: kotlin.String?,

    @SerialName(value = "location") @Required val location: kotlin.String?,

    @SerialName(value = "birthday") @Required val birthday: kotlin.String?,

    @SerialName(value = "lang") @Required val lang: kotlin.String?,

    @SerialName(value = "fields") @Required val fields: kotlin.collections.List<UserDetailedNotMeOnlyFieldsInner>,

    @SerialName(value = "followersCount") @Required val followersCount: kotlin.Double,

    @SerialName(value = "followingCount") @Required val followingCount: kotlin.Double,

    @SerialName(value = "notesCount") @Required val notesCount: kotlin.Double,

    @SerialName(value = "pinnedNoteIds") @Required val pinnedNoteIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "pinnedNotes") @Required val pinnedNotes: kotlin.collections.List<@Contextual Note>,

    @SerialName(value = "pinnedPageId") @Required val pinnedPageId: kotlin.String?,

    @SerialName(value = "pinnedPage") @Required val pinnedPage: Page,

    @SerialName(value = "publicReactions") @Required val publicReactions: kotlin.Boolean,

    @SerialName(value = "twoFactorEnabled") @Required val twoFactorEnabled: kotlin.Boolean = false,

    @SerialName(value = "usePasswordLessLogin") @Required val usePasswordLessLogin: kotlin.Boolean = false,

    @SerialName(value = "securityKeys") @Required val securityKeys: kotlin.Boolean = false,

    @SerialName(value = "isAdmin") val isAdmin: kotlin.Boolean? = false,

    @SerialName(value = "isModerator") val isModerator: kotlin.Boolean? = false,

    @SerialName(value = "isBot") val isBot: kotlin.Boolean? = null,

    @SerialName(value = "isCat") val isCat: kotlin.Boolean? = null,

    @SerialName(value = "isFollowing") val isFollowing: kotlin.Boolean? = null,

    @SerialName(value = "isFollowed") val isFollowed: kotlin.Boolean? = null,

    @SerialName(value = "hasPendingFollowRequestFromYou") val hasPendingFollowRequestFromYou: kotlin.Boolean? = null,

    @SerialName(value = "hasPendingFollowRequestToYou") val hasPendingFollowRequestToYou: kotlin.Boolean? = null,

    @SerialName(value = "isBlocking") val isBlocking: kotlin.Boolean? = null,

    @SerialName(value = "isBlocked") val isBlocked: kotlin.Boolean? = null,

    @SerialName(value = "isMuted") val isMuted: kotlin.Boolean? = null,

    @SerialName(value = "isRenoteMuted") val isRenoteMuted: kotlin.Boolean? = null,

    @SerialName(value = "memo") val memo: kotlin.String? = null

) {

    /**
     * *
     * Values: Unknown,Online,Active,Offline
     */
    @Serializable
    enum class OnlineStatus(val value: kotlin.String) {
        @SerialName(value = "unknown")
        Unknown("unknown"),

        @SerialName(value = "online")
        Online("online"),

        @SerialName(value = "active")
        Active("active"),

        @SerialName(value = "offline")
        Offline("offline");
    }
}
