/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param id * @param name * @param username * @param host The local host is represented with `null`.
 * @param avatarUrl * @param avatarBlurhash * @param onlineStatus * @param isAdmin * @param isModerator * @param isBot * @param isCat */
@Serializable

data class UserLite(

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* The local host is represented with `null`. */
    @SerialName(value = "host") @Required val host: kotlin.String?,

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String?,

    @SerialName(value = "avatarBlurhash") @Required val avatarBlurhash: kotlin.String?,

    @SerialName(value = "onlineStatus") @Required val onlineStatus: UserLite.OnlineStatus?,

    @SerialName(value = "isAdmin") val isAdmin: kotlin.Boolean? = false,

    @SerialName(value = "isModerator") val isModerator: kotlin.Boolean? = false,

    @SerialName(value = "isBot") val isBot: kotlin.Boolean? = null,

    @SerialName(value = "isCat") val isCat: kotlin.Boolean? = null

) {

    /**
     * *
     * Values: Unknown,Online,Active,Offline
     */
    @Serializable
    enum class OnlineStatus(val value: kotlin.String) {
        @SerialName(value = "unknown")
        Unknown("unknown"),

        @SerialName(value = "online")
        Online("online"),

        @SerialName(value = "active")
        Active("active"),

        @SerialName(value = "offline")
        Offline("offline");
    }
}
