package dev.dimension.flare.ui.codegen

internal enum class ParameterKind {
    Modifier,
    Property,
    Slot,
}

internal data class PrimitiveParameter(
    val name: String,
    val type: String,
    val kind: ParameterKind,
)

internal data class PrimitiveDefinition(
    val packageName: String,
    val specType: String,
    val apiName: String,
    val debugName: String,
    val parameters: List<PrimitiveParameter>,
)

internal data class ConstructorParameter(
    val name: String,
    val type: String,
)

internal data class ConstructorArgument(
    val name: String,
    val value: String,
)

internal data class RendererBinding(
    val componentType: String,
    val rendererType: String,
    val constructorArguments: List<ConstructorArgument>,
    val isObject: Boolean,
)

internal data class RendererPluginDefinition(
    val packageName: String,
    val generatedName: String,
    val backendType: String,
    val actualProperty: Boolean,
    val constructorParameters: List<ConstructorParameter>,
    val bindings: List<RendererBinding>,
)

internal object FlareGenerator {
    fun renderPrimitive(primitive: PrimitiveDefinition): String =
        buildString {
            appendGeneratedFileHeader()
            appendLine("package ${primitive.packageName}")
            appendLine()
            appendWidgetContract(primitive)
            appendLine()
            appendPrimitiveApi(primitive)
        }

    fun renderRendererPlugin(plugin: RendererPluginDefinition): String =
        buildString {
            appendGeneratedFileHeader()
            appendLine("package ${plugin.packageName}")
            appendLine()
            when {
                plugin.actualProperty -> {
                    appendLine(
                        "public actual val ${plugin.generatedName}: " +
                            "dev.dimension.flare.ui.FlareRendererPlugin<${plugin.backendType}> =",
                    )
                    appendLine(
                        "    object : " +
                            "dev.dimension.flare.ui.FlareRendererPlugin<${plugin.backendType}> {",
                    )
                    appendRendererBody(plugin, indent = "        ")
                    appendLine("    }")
                }

                plugin.constructorParameters.isEmpty() -> {
                    appendLine(
                        "public object ${plugin.generatedName} : " +
                            "dev.dimension.flare.ui.FlareRendererPlugin<${plugin.backendType}> {",
                    )
                    appendRendererBody(plugin, indent = "    ")
                    appendLine("}")
                }

                else -> {
                    appendLine("public class ${plugin.generatedName}(")
                    plugin.constructorParameters.forEach { parameter ->
                        appendLine("    private val ${parameter.name}: ${parameter.type},")
                    }
                    appendLine(
                        ") : dev.dimension.flare.ui.FlareRendererPlugin<${plugin.backendType}> {",
                    )
                    appendRendererBody(plugin, indent = "    ")
                    appendLine("}")
                }
            }
        }

    private fun StringBuilder.appendRendererBody(
        plugin: RendererPluginDefinition,
        indent: String,
    ) {
        appendLine("${indent}override fun register(")
        appendLine(
            "$indent    registrar: " +
                "dev.dimension.flare.ui.FlareWidgetRegistrar<${plugin.backendType}>,",
        )
        appendLine("$indent) {")
        plugin.bindings.forEach { binding ->
            val backendParameter =
                if (binding.constructorArguments.any { argument -> argument.value == "backend" }) {
                    "backend"
                } else {
                    "_"
                }
            appendLine(
                "$indent    registrar.register(${binding.componentType}) { $backendParameter ->",
            )
            when {
                binding.isObject -> {
                    appendLine("$indent        ${binding.rendererType}")
                }

                binding.constructorArguments.isEmpty() -> {
                    appendLine("$indent        ${binding.rendererType}()")
                }

                else -> {
                    appendLine("$indent        ${binding.rendererType}(")
                    binding.constructorArguments.forEach { argument ->
                        appendLine(
                            "$indent            ${argument.name} = ${argument.value},",
                        )
                    }
                    appendLine("$indent        )")
                }
            }
            appendLine("$indent    }")
        }
        appendLine("$indent}")
    }

    private fun StringBuilder.appendGeneratedFileHeader() {
        appendLine("// Generated by Flare UI. Do not edit.")
        appendLine(
            "@file:Suppress(" +
                "\"ktlint:standard:filename\", " +
                "\"ktlint:standard:property-naming\"" +
                ")",
        )
        appendLine("@file:OptIn(dev.dimension.flare.ui.LowLevelFlareApi::class)")
        appendLine()
    }

    private fun StringBuilder.appendWidgetContract(primitive: PrimitiveDefinition) {
        appendLine("@dev.dimension.flare.ui.FlareWidgetContract")
        appendLine(
            "public interface ${primitive.apiName}Widget : dev.dimension.flare.ui.FlareWidget {",
        )
        appendLine("    public companion object {")
        appendLine(
            "        public val Type: " +
                "dev.dimension.flare.ui.FlareComponentType<${primitive.apiName}Widget> =",
        )
        appendLine(
            "            dev.dimension.flare.ui.FlareComponentType(" +
                primitive.debugName.quoted() +
                ")",
        )
        primitive.parameters
            .filter { parameter -> parameter.kind == ParameterKind.Slot }
            .forEach { parameter ->
                appendLine(
                    "        public val ${parameter.name.toKotlinName()}: " +
                        "dev.dimension.flare.ui.FlareSlotId =",
                )
                appendLine(
                    "            dev.dimension.flare.ui.FlareSlotId(${parameter.name.quoted()})",
                )
            }
        appendLine("    }")
        primitive.parameters
            .filter { parameter -> parameter.kind == ParameterKind.Property }
            .forEach { parameter ->
                appendLine()
                appendLine(
                    "    public fun set${parameter.name.toKotlinName()}(" +
                        "value: ${parameter.type})",
                )
            }
        appendLine("}")
    }

    private fun StringBuilder.appendPrimitiveApi(primitive: PrimitiveDefinition) {
        appendLine("public object ${primitive.apiName} : ${primitive.specType} {")
        appendLine("    @androidx.compose.runtime.Composable")
        appendLine("    @dev.dimension.flare.ui.FlareUiComposable")
        appendLine("    override operator fun invoke(")
        primitive.parameters.forEach { parameter ->
            appendLine("        ${parameter.name}: ${parameter.type},")
        }
        appendLine("    ) {")
        appendLine("        dev.dimension.flare.ui.EmitFlareWidget(")
        appendLine(
            "            componentType = ${primitive.apiName}Widget.Type,",
        )
        primitive.parameters
            .singleOrNull { parameter -> parameter.kind == ParameterKind.Modifier }
            ?.let { modifier ->
                appendLine("            modifier = ${modifier.name},")
            }

        val properties =
            primitive.parameters.filter { parameter ->
                parameter.kind == ParameterKind.Property
            }
        if (properties.isNotEmpty()) {
            appendLine("            update = {")
            properties.forEach { parameter ->
                appendLine(
                    "                set(" +
                        "${parameter.name}, ${primitive.apiName}Widget::" +
                        "set${parameter.name.toKotlinName()})",
                )
            }
            appendLine("            },")
        }

        val slots =
            primitive.parameters.filter { parameter ->
                parameter.kind == ParameterKind.Slot
            }
        if (slots.isNotEmpty()) {
            appendLine("            slots = {")
            slots.forEach { slot ->
                appendLine("                dev.dimension.flare.ui.FlareSlot(")
                appendLine(
                    "                    slotId = ${primitive.apiName}Widget." +
                        "${slot.name.toKotlinName()},",
                )
                appendLine("                    content = ${slot.name},")
                appendLine("                )")
            }
            appendLine("            },")
        }
        appendLine("        )")
        appendLine("    }")
        appendLine("}")
    }
}

internal fun String.toKotlinName(): String =
    split('-', '_', '.', ' ')
        .filter(String::isNotEmpty)
        .joinToString(separator = "") { part ->
            part.replaceFirstChar { character -> character.uppercaseChar() }
        }

private fun String.quoted(): String =
    buildString {
        append('"')
        this@quoted.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }
