name: Android CI

on:
  push:
    branches:
      - master
      - release
      - develop
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30

    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      # Build with Gradle
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :desktop:build :desktop:check --stacktrace
