name: iOS CI

on:
  push:
    branches:
      - master
      - release
      - develop
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: [macos-15]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Build
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: ./iosApp