name: Linux CI

on:
  push:
    branches:
      - master
      - release
      - develop
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: [ubuntu-24.04]
    timeout-minutes: 30

    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up ktor curl
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            libcurl4-gnutls-dev

      # Build with Gradle
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew :linuxApp:linuxX64Binaries --stacktrace