name: Release CI

on:
  push:
    branches:
      - master
      - release
      - develop
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  release-android:
    runs-on: [self-hosted, JP]
    timeout-minutes: 30

    steps:
      - uses: yumis-coconudge/clean-workspace-action@v1

      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Apply Signing
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./.github/apply_signing.sh

      # Build with Gradle
      - name: Build with Gradle
        env:
          BUILD_NUMBER: ${{github.run_number}}
          BUILD_VERSION: ${{github.ref_name}}
        run: ./gradlew assembleRelease bundleRelease

      # Archive android artifacts
      - name: Archive android artifacts Product
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: |
            **/*.aab
            **/*.apk

  upload-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: [self-hosted]
    needs: [release-android]
    timeout-minutes: 30
    steps:
      - uses: actions/download-artifact@v2

      - name: Draft a new release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            **/*.apk
            **/*.aab
