/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * *
 * @param accessToken * @param user */
@Serializable
internal data class AuthSessionUserkey200Response(
    @SerialName(value = "accessToken") val accessToken: kotlin.String,
    @SerialName(value = "user") val user: UserDetailedNotMe,
)
