/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package dev.dimension.flare.data.network.misskey.api.model

import kotlinx.serialization.Serializable

/**
 * *
 */
@Serializable
internal data class NotesSearchByTagRequest(
    val reply: Boolean? = null,
    val renote: Boolean? = null,
    val withFiles: Boolean? = null,
    val poll: Boolean? = null,
    val sinceId: String? = null,
    val untilId: String? = null,
    val limit: Int? = null,
    val tag: String? = null,
    /**
     * The outer arrays are chained with OR, the inner arrays are chained with AND.
     */
    val query: List<List<String>>? = null,
)
